Abort install if cannot assign required variables

diff --git a/build/common/001-Variables b/build/common/001-Variables
--- a/build/common/001-Variables
+++ b/build/common/001-Variables
@@ -1,26 +1,3 @@
-# Make sure that we are running on Telstra firmware
-if [ "$(uci -q get env.var._provisioning_code)" != "Telstra" ]
-then
-  echo "ERROR! This script is intended for devices with Telstra firmware. Exiting"
-  exit 1
-fi
-
-# Based on various pages https://hack-technicolor.readthedocs.io/en/stable/
-
-TARGET_VERSION=""
-for x in $(basename $0 | tr '-' "$IFS"); do
-  TARGET_VERSION=$x
-done
-
-if ! echo "$TARGET_VERSION" | grep -q '\.'; then
-  echo "ERROR: Unable to determine Target Version!"
-  echo "       Did the script get renamed??"
-  echo "       Aborting..."
-  exit 1
-fi
-
-SCRIPT=$(basename $0 | sed "s/-$TARGET_VERSION//")
-
 CYAN="\033[4;36m"
 GREEN='\033[1;32m'
 GREY='\033[90m'
@@ -28,16 +5,38 @@ ORANGE='\033[0;33m'
 RED='\033[0;31m'
 NC='\033[0m' # No Color
 
-INSTALLED_RELEASE="$(grep -o -m 1 -E '[0-9][0-9][0-9][0-9]\.[0-9][0-9]\.[0-9][0-9]@[0-9][0-9]:[0-9][0-9]' /usr/share/transformer/mappings/rpc/gui.map 2>/dev/null)"
+abort_install() {
+  echo -e "${RED}*FATAL*:${NC} $*"
+  echo -e "${RED}ABORTED!${NC}"
+  exit 1
+}
+
+[ "$(uci -q get env.var._provisioning_code)" = "Telstra" ] || abort_install "This script is only intended for devices with Telstra firmware"
+
+TARGET_VERSION=""
+for x in $(basename $0 | tr '-' "$IFS"); do
+  TARGET_VERSION=$x
+done
+echo "$TARGET_VERSION" | grep -q '\.' || abort_install "Unable to determine Target Version! Did the script get renamed??"
+SCRIPT=$(basename $0 | sed "s/-$TARGET_VERSION//")
+
 VERSION=$(uci -q get version.@version[0].version | cut -d- -f1)
 FW_BASE=$(uci -q get version.@version[0].marketing_version)
-VARIANT=$(uci -q get env.var.variant_friendly_name | sed -e 's/TLS//')
+VARIANT=$(uci -q get env.var.variant_friendly_name | sed -e 's/TLS//' -e 's/vac//')
+MAC_HEX=$(uci -q get env.var.ssid_mac_postfix_r0)
 HOSTNAME=$(uci -q get system.@system[0].hostname)
+
+[ -n "$VERSION" ]  || abort_install "Failed to determine device firmware version?"
+[ -n "$FW_BASE" ]  || abort_install "Failed to determine device base firmware (marketing) version?"
+[ -n "$VARIANT" ]  || abort_install "Failed to determine device variant?"
+[ -n "$MAC_HEX" ]  || abort_install "Failed to determine MAC representation?"
+[ -n "$HOSTNAME" ] || abort_install "Failed to determine device hostname?"
+
 DFLT_USR=$(uci -q get web.uidefault.defaultuser)
 FW_UPGRD=$(uci -q get web.uidefault.upgradefw)
-MAC=$(uci -q get env.var.ssid_mac_postfix_r0)
-TITLE="$(grep -o 'title>.*</title' /www/docroot/gateway.lp | cut -d'>' -f2 | cut -d'<' -f1 | grep -v 'ngx.print')"
 
+INSTALLED_RELEASE="$(grep -o -m 1 -E '[0-9][0-9][0-9][0-9]\.[0-9][0-9]\.[0-9][0-9]@[0-9][0-9]:[0-9][0-9]' /usr/share/transformer/mappings/rpc/gui.map 2>/dev/null)"
+TITLE="$(grep -o 'title>.*</title' /www/docroot/gateway.lp | cut -d'>' -f2 | cut -d'<' -f1 | grep -v 'ngx.print')"
 BG_RFRSH="$(grep -o 'window.autoRefreshEnabled=[^;]*;' /www/docroot/gateway.lp | cut -d= -f2 | cut -d';' -f1)"
 [ -z "$BG_RFRSH" ] && BG_RFRSH="true"
 
