Reworked chart colours again

diff --git a/build/common/002-Parameter-Processing b/build/common/002-Parameter-Processing
--- a/build/common/002-Parameter-Processing
+++ b/build/common/002-Parameter-Processing
@@ -8,13 +8,15 @@ FILENAME=$(basename $0)
 while getopts :c:d:f:h:i:l:p:rt:uv:yTVW option
 do
  case "${option}" in
-   c) case "$(echo ${OPTARG} | tr "BGMOPR" "bgmopr" | sed 's/\(.\)\(.*\)/\1/')" in
+   c) case "$(echo ${OPTARG} | sed 's/\(.\)\(.*\)/\1/')" in
         b) COLOR=blue;; 
         g) COLOR=green;; 
         o) COLOR=orange;; 
         p) COLOR=purple;; 
         r) COLOR=red;; 
-        *) COLOR=monochrome;;
+        m) COLOR=monochrome;;
+        M) COLOR=MONOCHROME;;
+        *) echo "ERROR: Unknown color option - $OPTARG"; exit 2;;
       esac;;
    d) case "${OPTARG}" in y|Y) FIX_DFLT_USR=y; DFLT_USR='admin';; n|N) FIX_DFLT_USR=y; DFLT_USR='';;  *) echo 'WARNING: -d valid options are y or n';; esac;;
    f) case "${OPTARG}" in y|Y) FIX_FW_UPGRD=y; FW_UPGRD='1';;     n|N) FIX_FW_UPGRD=y; FW_UPGRD='0';; *) echo 'WARNING: -f valid options are y or n';; esac;;
@@ -104,39 +106,39 @@ do
    W) WRAPPER=y;;
    ?) echo "Optional parameters:"
       echo " Control Options:"
-      echo " -d y|n         : Enable (y) or Disable (n) Default user (i.e. GUI access without password)"
-      echo "                    (Default is current setting)"
-      echo " -f y|n         : Enable (y) or Disable (n) firmware upgrade in the web GUI"
-      echo "                    (Default is current setting)"
-      echo " -p y|n         : Use decrypted text (y) or masked password (n) field for SIP Profile passwords"
-      echo "                    (Default is current setting i.e (n) by default)"
-      echo " -v y|n         : Enable (y) check for new releases and show 'Update Available' button in GUI, or Disable (n)"
-      echo "                    (Default is current setting or (y) for first time installs)"
+      echo " -d y|n           : Enable (y) or Disable (n) Default user (i.e. GUI access without password)"
+      echo "                     (Default is current setting)"
+      echo " -f y|n           : Enable (y) or Disable (n) firmware upgrade in the web GUI"
+      echo "                     (Default is current setting)"
+      echo " -p y|n           : Use decrypted text (y) or masked password (n) field for SIP Profile passwords"
+      echo "                     (Default is current setting i.e (n) by default)"
+      echo " -v y|n           : Enable (y) check for new releases and show 'Update Available' button in GUI, or Disable (n)"
+      echo "                     (Default is current setting or (y) for first time installs)"
       echo " Theme Options:"
-      echo " -c b|o|g|p|r|m : Set the theme highlight colour"
-      echo "                    b=blue o=orange g=green p=purple r=red m=monochrome"
-      echo "                    (Default is current setting, or (m) for light theme or (b) for night theme)"
+      echo " -c b|o|g|p|r|m|M : Set the theme highlight colour"
+      echo "                     b=blue o=orange g=green p=purple r=red m=monochrome M=monochrome (with monochrome charts)"
+      echo "                     (Default is current setting, or (m) for light theme or (b) for night theme)"
       echo " -h d|s|n|\"txt\" : Set the browser tabs title (Default is current setting)"
-      echo "                    (d)=$VARIANT (s)=$VARIANT-$MAC (n)=$HOSTNAME (\"txt\")=Specified \"txt\""
-      echo " -i y|n         : Show (y) or hide (n) the card icons"
-      echo "                    (Default is current setting, or (n) for light theme and (y) for night theme)"
-      echo " -l y|n         : Keep the Telstra landing page (y) or de-brand the landing page (n)"
-      echo "                    (Default is current setting, or (n) if no theme has been applied)"
-      echo " -t l|n|t|m     : Set a light (l), night (n), or Telstra-branded Classic (t) or Modern (m) theme"
-      echo "                    (Default is current setting, or Telstra Classic if no theme has been applied)"
-      echo " -T             : Apply theme ONLY - bypass all other processing"
+      echo "                     (d)=$VARIANT (s)=$VARIANT-$MAC (n)=$HOSTNAME (\"txt\")=Specified \"txt\""
+      echo " -i y|n           : Show (y) or hide (n) the card icons"
+      echo "                      (Default is current setting, or (n) for light theme and (y) for night theme)"
+      echo " -l y|n           : Keep the Telstra landing page (y) or de-brand the landing page (n)"
+      echo "                      (Default is current setting, or (n) if no theme has been applied)"
+      echo " -t l|n|t|m       : Set a light (l), night (n), or Telstra-branded Classic (t) or Modern (m) theme"
+      echo "                      (Default is current setting, or Telstra Classic if no theme has been applied)"
+      echo " -T               : Apply theme ONLY - bypass all other processing"
       echo " Update Options:"
-      echo " -u             : Check for and download any changes to this script (may be newer than latest release version)"
-      echo "                    When specifying the -u option, it must be the ONLY parameter specifed."
+      echo " -u               : Check for and download any changes to this script (may be newer than latest release version)"
+      echo "                      When specifying the -u option, it must be the ONLY parameter specifed."
       if [ $WRAPPER = y ]; then
-      echo " -U             : Download the latest release, including utility scripts (will overwrite all existing script versions)."
-      echo "                    When specifying the -U option, it must be the ONLY parameter specifed."
+      echo " -U               : Download the latest release, including utility scripts (will overwrite all existing script versions)."
+      echo "                      When specifying the -U option, it must be the ONLY parameter specifed."
       fi
       echo " Miscellaneous Options:"
-      echo " -r             : Restore changed GUI files to their original state (config changes are NOT restored)"
-      echo "                    When specifying the -r option, it must be the ONLY parameter specifed."
-      echo " -y             : Bypass confirmation prompt (answers 'y')"
-      echo " -V             : Show the release number of this script, the current installed release, and the latest available release on GitHub"
+      echo " -r               : Restore changed GUI files to their original state (config changes are NOT restored)"
+      echo "                     When specifying the -r option, it must be the ONLY parameter specifed."
+      echo " -y               : Bypass confirmation prompt (answers 'y')"
+      echo " -V               : Show the release number of this script, the current installed release, and the latest available release on GitHub"
       echo 
       echo "NOTE #1: Theme (-t) does not need to be re-specified when re-running the script: current state will be 'remembered'"
       echo "         between executions (unless you execute with the -r option, which will remove all state information)"
