Added summary chart card [#40]

diff --git a/build/common/002-Parameter-Processing b/build/common/002-Parameter-Processing
--- a/build/common/002-Parameter-Processing
+++ b/build/common/002-Parameter-Processing
@@ -6,7 +6,7 @@ THEME_ONLY='n'
 
 FILENAME=$(basename $0)
 
-while getopts :a:c:d:f:h:i:l:p:rt:uv:yTVW-: option
+while getopts :a:c:d:f:h:i:l:p:rt:uv:yC:TVW-: option
 do
  case "${option}" in
    -) case "${OPTARG}" in 
@@ -95,6 +95,10 @@ do
       exit;;
    v) if [ "$(echo ${OPTARG} | tr "YN" "yn" | sed 's/\(.\)\(.*\)/\1/')" = "y" ]; then UPDATE_BTN=y; else UPDATE_BTN=n; fi;;
    y) YES=y;;
+   C) case "${OPTARG}" in
+        n|s|i) CHART_CARDS="$OPTARG";; 
+        *) echo "ERROR: Unknown chart card option - $OPTARG"; exit 2;;
+      esac;;
    T) THEME_ONLY=y;;
    V) LATEST_RELEASE=$(curl -m 1 -q -s -k -L -r0-9 https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/VERSION.txt)
       echo "002@$(date +%H:%M:%S): This Release       $RELEASE"
@@ -134,6 +138,10 @@ do
       echo "                      (Default is current setting, or (n) if no theme has been applied)"
       echo " -t l|n|t|m       : Set a light (l), night (n), or Telstra-branded Classic (t) or Modern (m) theme"
       echo "                      (Default is current setting, or Telstra Classic if no theme has been applied)"
+      echo " -C n|s|i         : Keep or remove chart cards"
+      echo "                     n=No Chart Cards will be available"
+      echo "                     s=Only the Summary Chart Card will be available"
+      echo "                     i=Only the Individual Chart Cards will be available (default)"
       echo " -T               : Apply theme ONLY - bypass all other processing"
       echo " Update Options:"
       echo " -u               : Check for and download any changes to this script (may be newer than latest release version)"
