Added new "classic" theme

diff --git a/build/common/002-Parameter-Processing b/build/common/002-Parameter-Processing
--- a/build/common/002-Parameter-Processing
+++ b/build/common/002-Parameter-Processing
@@ -39,7 +39,7 @@ Optional parameters:
                     (Default is current setting, or (n) for light theme and (y) for night theme)
  -l y|n           Keep the Telstra landing page (y) or de-brand the landing page (n)
                     (Default is current setting, or (n) if no theme has been applied)
- -t l|n|t|m       Set a light (l), night (n), or Telstra-branded Classic (t) or Modern (m) theme
+ -t l|n|c|t|m     Set a light (l), night (n), classic (c) or Telstra-branded Classic (t) or Modern (m) theme
                     (Default is current setting, or Telstra Classic if no theme has been applied)
  -C n|s|i         Keep or remove chart cards
                    n=No Chart Cards will be available
@@ -105,13 +105,12 @@ do
    p) if [ "$(echo ${OPTARG} | tr "YN" "yn" | sed 's/\(.\)\(.*\)/\1/')" = "y" ]; then SIP_PWDS=y; else SIP_PWDS=n; fi;;
    r) RESTORE=y;;
    t) case "${OPTARG}" in
-        g) THEME=night; COLOR=green; KEEPLP=n; echo WARNING: -tg deprecated. Use -tn -cg in future;;
-        o) THEME=night; COLOR=orange; KEEPLP=n; echo WARNING: -to deprecated. Use -tn -co in future;;
-        p) THEME=night; COLOR=purple; KEEPLP=n; echo WARNING: -tp deprecated. Use -tn -cp in future;;
+        c) THEME=classic; COLOR=blue; KEEPLP=n;;
         l) THEME=light; COLOR=monochrome; KEEPLP=n;;
         m) THEME=telstramodern; COLOR=blue; KEEPLP=y;;
         n) THEME=night; COLOR=blue; KEEPLP=n;;
-        *) THEME=telstra; COLOR=blue; KEEPLP=y;;
+        t) THEME=telstra; COLOR=blue; KEEPLP=y;;
+        *) echo "ERROR: Unknown theme option - $OPTARG"; exit 2;;
       esac;;
    u) RESULT=$(curl -m 5 -s -k -L -I https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/$FILENAME | sed 's/\r//')
       if [ $? -ne 0 ]
