flock not available on older firmware (#63)

diff --git a/build/common/030-Confirm b/build/common/030-Confirm
--- a/build/common/030-Confirm
+++ b/build/common/030-Confirm
@@ -68,10 +68,10 @@ if [ "$MINIFY" = y ]; then
   echo -e "[$SCRIPT]: \033[0;33mWARNING! Experimental Lua GUI code minification is enabled!\033[0m"
 fi
 
-echo [$SCRIPT]: If you wish to proceed, enter y otherwise just press [Enter] to stop.
 if [ $YES = y ]; then
   REPLY=y
 else
+  echo [$SCRIPT]: If you wish to proceed, enter y otherwise just press [Enter] to stop.
   read
 fi
 if [ "$REPLY" != "y" -a "$REPLY" != "Y" ]; then
@@ -79,4 +79,7 @@ if [ "$REPLY" != "y" -a "$REPLY" != "Y" ]; then
 fi
 
 echo [$SCRIPT]: IMPORTANT NOTE - You can restore changed GUI files to their original state by running: $0 -r
+
+LOCK="/var/run/${SCRIPT}"
+lock -n $LOCK || { echo "ERROR: $SCRIPT already running!"; exit 2; }
 
diff --git a/utilities/de-telstra b/utilities/de-telstra
--- a/utilities/de-telstra
+++ b/utilities/de-telstra
@@ -337,8 +337,7 @@ if [ $SAVE_DEFAULTS = y -o $SHOW_DEFAULTS = y -o $__YES = n ]; then
 fi
 
 LOCK="/var/run/${SCRIPT}"
-exec 200>$LOCK
-flock -n 200 || { echo "[$SCRIPT]: ERROR! Already running!"; exit 2; }
+lock -n $LOCK || { echo "[$SCRIPT]: ERROR! Already running!"; exit 2; }
 
 status2text() {
   if [ "$1" = "0" ]; then
@@ -1391,5 +1390,6 @@ echo [$SCRIPT]: Cleaning up broken links in /etc/rc.d
 find /etc/rc.d -type l ! -exec test -e {} \; -exec rm {} \;
 
 echo [$SCRIPT]: Done!
+lock -u $LOCK
 [ -f $LOCK ] && rm $LOCK
 [ $__ROOT_PWD_REMINDER = y ] && echo -e "[$SCRIPT]: \033[1;32mNOTE: If you haven't changed the root password, you should do it now...\033[0m"
diff --git a/utilities/mtd-backup b/utilities/mtd-backup
--- a/utilities/mtd-backup
+++ b/utilities/mtd-backup
@@ -1,9 +1,6 @@
 #!/bin/sh
 
 SCRIPT="$(basename $0)"
-LOCK="/var/run/${SCRIPT}"
-exec 200>$LOCK
-flock -n 200 || { echo "[$SCRIPT] ERROR! Already running!"; exit 2; }
 
 SERIAL=$(uci get env.var.serial)
 VARIANT=$(uci -q get env.var.variant_friendly_name)
@@ -147,6 +144,9 @@ fi
 if [ "$REPLY" != "y" -a "$REPLY" != "Y" ]; then
   exit
 fi
+
+LOCK="/var/run/${SCRIPT}"
+lock -n $LOCK || { echo "[$SCRIPT] ERROR! Already running!"; exit 2; }
 
 if [ $CRON = Y ]; then
   if [ $CRON_ACTION = remove ]; then
@@ -312,6 +312,9 @@ if [ $FLUSH = Y ]; then
   sync
   echo 1 > /proc/sys/vm/drop_caches
 fi
+
+lock -u $LOCK
+[ -f $LOCK ] && rm $LOCK
 
 [ $DEBUG = Y ] && $LOGGER user.debug "Backup completed in $(( $(date +%s) - $STARTED )) seconds"
 
diff --git a/utilities/set-web-admin-password b/utilities/set-web-admin-password
--- a/utilities/set-web-admin-password
+++ b/utilities/set-web-admin-password
@@ -2,8 +2,7 @@
 
 SCRIPT="$(basename $0)"
 LOCK="/var/run/${SCRIPT}"
-exec 200>$LOCK
-flock -n 200 || { echo "ERROR: $SCRIPT already running!"; exit 2; }
+lock -n $LOCK || { echo "ERROR: $SCRIPT already running!"; exit 2; }
 
 if [ -z "$1" ]; then
   echo "ERROR: No password specified"
@@ -35,3 +34,6 @@ uci commit web
 /etc/init.d/nginx restart
 
 echo Web GUI password for admin set to: $KEY
+
+lock -u $LOCK
+[ -f $LOCK ] && rm $LOCK
