Abort if cannot determine environment

diff --git a/utilities/de-telstra b/utilities/de-telstra
--- a/utilities/de-telstra
+++ b/utilities/de-telstra
@@ -1,11 +1,17 @@
 #!/bin/sh
-# Make sure that we are running on Telstra firmware
-if [ "$(uci -q get env.var._provisioning_code)" != "Telstra" ]; then
-  echo "ERROR! This script is intended for devices with Telstra firmware. Exiting"
-  exit 1
-fi
+GREEN='\033[1;32m'
+GREY='\033[90m'
+ORANGE='\033[0;33m'
+RED='\033[0;31m'
+NC='\033[0m' # No Color
 
-# Based on https://hack-technicolor.readthedocs.io/en/stable/Hardening/
+abort_install() {
+  echo -e "${RED}*FATAL*:${NC} $*"
+  echo -e "${RED}ABORTED!${NC}"
+  exit 1
+}
+
+[ "$(uci -q get env.var._provisioning_code)" = "Telstra" ] || abort_install "This script is only intended for devices with Telstra firmware"
 
 SCRIPT="$(basename $0)"
 
@@ -13,13 +19,11 @@ VERSION=$(uci -q get version.@version[0].marketing_version)
 VARIANT=$(uci -q get env.var.variant_friendly_name | sed -e 's/TLS//')
 MAC_HEX=$(uci -q get env.var.ssid_mac_postfix_r0)
 
-cat /proc/cpuinfo | grep -q 'ARMv7 Processor rev 1 (v7l)' && ARMv7=1 || ARMv7=0
+[ -n "$VERSION" ] || abort_install "Failed to determine device firmware version?"
+[ -n "$VARIANT" ] || abort_install "Failed to determine device variant?"
+[ -n "$MAC_HEX" ] || abort_install "Failed to determine MAC representation?"
 
-GREEN='\033[1;32m'
-GREY='\033[90m'
-ORANGE='\033[0;33m'
-RED='\033[0;31m'
-NC='\033[0m' # No Color
+cat /proc/cpuinfo | grep -q 'ARMv7 Processor rev 1 (v7l)' && ARMv7=1 || ARMv7=0
 
 RESTART_SERVICES=y
 SAVE_DEFAULTS=n
