Disable NFC in minimum memory mode (if installed)

diff --git a/utilities/de-telstra b/utilities/de-telstra
--- a/utilities/de-telstra
+++ b/utilities/de-telstra
@@ -53,12 +53,13 @@ Options:
  -u u|y|n              UPnP Service:            u=unchanged y=Enable n=Disable
  -m u|y|n            * MultiAP (EasyMesh):      u=unchanged y=Enable n=Disable
  -g u|y|n            * DumaOS (Game Optimiser): u=unchanged y=Enable n=Disable
+ -q u|y|n            * NFC:                     u=unchanged y=Enable n=Disable
  -w u|y|n              WPS on non-Guest and non-Backhaul SSIDs: u=unchanged y=Enable n=Disable
  -F u|y|n              Factory reset root protection: u=unchanged y=Enable n=Disable
                           NOTE: Installation of tch-gui-unhide will ALWAYS enable RTFD protection!
  -A                    Equivalent to: -hd -dg -an -cn -fn -rn -un -wn -Fy
  -S                    Equivalent to: -hs -dg -an -cn -fn -rn -un -wn -Fy
- -M                    Minimum memory mode: Equivalent to: -an -cn -fn -rn -tn -en -un -mn -gn -Fy
+ -M                    Minimum memory mode: Equivalent to: -an -cn -fn -rn -tn -en -un -mn -gn -qn -Fy
                         PLUS stops and disables the associated services
  -R                    Reset to device defaults
                         (equivalent to: -hmymodem -dmodem -na -ay -cy -fy -py -ry -ty -ey -uy -my -gy -wy -Fn)
@@ -136,6 +137,13 @@ else
   SRV_multiap=-1
 fi
 
+if [ -e /etc/config/nfc ]
+then
+  SRV_nfc=0
+else
+  SRV_nfc=-1
+fi
+
 PACKAGES_TO_REMOVE=""
 
 # Options
@@ -150,6 +158,7 @@ HOST='u'
 LITE='n'
 MMPBX='u'
 MULTIAP='u'
+NFC='u'
 NS='u'
 OPKG='n'
 POWER='u' 
@@ -166,7 +175,7 @@ MONITORING='n'
 NTP='n'
 NOEXEC='n'
 
-while getopts :a:c:d:e:f:g:h:k:m:n:op:r:t:u:w:AF:MRSU option
+while getopts :a:c:d:e:f:g:h:k:m:n:op:q:r:t:u:w:AF:MRSU option
 do
  case "${option}" in
   a)  case "${OPTARG}" in y) ALG='1';; n) ALG='0';; u) ALG='u';; *) ALG='u'; echo 'ERROR: -a valid options are y, n, or u'; exit 1;; esac;;
@@ -181,13 +190,14 @@ do
   n)  NS=${OPTARG};;
   o)  OPKG='y';;
   p)  case "${OPTARG}" in y) POWER='y';; n) POWER='n';; u) POWER='u';; *) POWER='u'; echo 'ERROR: -p valid options are y, n, or u'; exit 1;; esac;;
+  q)  case "${OPTARG}" in y) NFC='1';; n) NFC='0';; u) NFC='u';; *) NFC='u'; echo 'ERROR: -q valid options are y, n, or u'; exit 1;; esac;;
   r)  case "${OPTARG}" in y) PRNTR='1';; n) PRNTR='0';; u) PRNTR='u';; *) PRNTR='u'; echo 'ERROR: -r valid options are y, n, or u'; exit 1;; esac;;
   t)  case "${OPTARG}" in y) MMPBX='1';; n) MMPBX='0';; u) MMPBX='u';; *) MMPBX='u'; echo 'ERROR: -t valid options are y, n, or u'; exit 1;; esac;;
   u)  case "${OPTARG}" in y) UPNP='1';; n) UPNP='0';; u) UPNP='u';; *) UPNP='u'; echo 'ERROR: -u valid options are y, n, or u'; exit 1;; esac;;
   w)  case "${OPTARG}" in y) WPS='1';; n) WPS='0';; u) WPS='u';; *) WPS='u'; echo 'ERROR: -w valid options are y, n, or u'; exit 1;; esac;;
   A)  HOST='d'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1';;
   F)  case "${OPTARG}" in y) ROOT_PROTECT='1';; n) ROOT_PROTECT='0';; u) ROOT_PROTECT='u';; *) ROOT_PROTECT='u'; echo 'ERROR: -F valid options are y, n, or u'; exit 1;; esac;;
-  M)  LITE='y'; ALG='0'; DECT='0'; DLNAD='0'; DUMAOS='0'; MMPBX='0'; MULTIAP='0'; PRNTR='0'; SAMBA='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1';;
+  M)  LITE='y'; ALG='0'; DECT='0'; DLNAD='0'; DUMAOS='0'; MMPBX='0'; MULTIAP='0'; NFC='0'; PRNTR='0'; SAMBA='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1';;
   R)  LITE='R'; HOST='mymodem'; DOMAIN='modem'; NS='a'; ALG='1'; DLNAD='1'; DUMAOS='0'; SAMBA='1'; MULTIAP='1'; POWER='y'; PRNTR='1'; MMPBX='1'; DECT='1'; UPNP='1'; ROOT_PROTECT='0';;
   S)  HOST='s'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1';;
   U)  upgrade;;
@@ -854,7 +864,7 @@ then
     uci set dumaos.tr69.dumaos_enabled="$DUMAOS"
     uci commit dumaos
     SRV_dumaos=$(( $SRV_dumaos + 1 ))
-  echo [$SCRIPT]: DumaOS $(status2text $DUMAOS)
+    echo [$SCRIPT]: DumaOS $(status2text $DUMAOS)
   fi
 fi
 
@@ -882,6 +892,20 @@ then
 elif [ "$MULTIAP" != "u" ]
 then
   echo [$SCRIPT]: MultiAP not found on device
+fi
+
+if [ $SRV_nfc -ge 0 ]
+then
+  NFC_NOW="$(uci -q get nfc.@nfc[0].enabled)"
+  if [ "$NFC" = "u" -o "$NFC_NOW" = "$NFC" ]
+  then
+    echo [$SCRIPT]: NFC unchanged \[$(status2text $NFC_NOW)\]
+  else
+    uci set nfc.@nfc[0].enabled="$NFC"
+    uci commit nfc
+    SRV_nfc=$(( $SRV_nfc + 1 ))
+    echo [$SCRIPT]: NFC $(status2text $NFC)
+  fi
 fi
 
 PWR_STATUS=$(pwrctl show | grep ENABLED | grep -v "Switch Deep Green Mode" | wc -l)
@@ -1016,6 +1040,7 @@ echo [$SCRIPT]: Applying required service changes...
 [ $SRV_monitor -gt 0 -a -e /etc/init.d/wifi-doctor-agent ] && /etc/init.d/wifi-doctor-agent reload > /dev/null 2>&1
 [ $SRV_multiap -gt 0 ] && { /etc/init.d/multiap_controller enable; /etc/init.d/multiap_agent enable; /etc/init.d/multiap_vendorextensions enable; /etc/init.d/multiap_controller restart; /etc/init.d/multiap_agent restart; /etc/init.d/multiap_vendorextensions restart; } > /dev/null 2>&1
 [ $SRV_network -gt 0 ] && /etc/init.d/network reload > /dev/null 2>&1
+[ $SRV_nfc -gt 0 ] && /etc/init.d/nfcd restart > /dev/null 2>&1
 [ $SRV_ntp -gt 0 ] && /etc/init.d/sysntpd restart > /dev/null 2>&1
 [ $SRV_samba -gt 0 -a -e /etc/init.d/samba-nmbd ] && { /etc/init.d/samba-nmbd enable; /etc/init.d/samba-nmbd reload; } > /dev/null 2>&1
 [ $SRV_samba -gt 0 ] && { /etc/init.d/samba enable; /etc/init.d/samba reload; } > /dev/null 2>&1
@@ -1037,6 +1062,7 @@ echo [$SCRIPT]: Applying required service changes...
   [ "$DUMAOS" = "0" -a $SRV_dumaos -ge 0 ] && { /etc/init.d/dumaos disable; /etc/init.d/ndhttpd disable; /etc/init.d/dumaos stop; /etc/init.d/ndhttpd stop; } > /dev/null 2>&1
   [ "$DUMAOS" = "0" -a $SRV_dumaos -ge 0 -a -e /etc/init.d/telemetry-daemon ] && { /etc/init.d/telemetry-daemon disable; /etc/init.d/telemetry-daemon stop; } > /dev/null 2>&1
   [ "$MMPBX" = "0" ] && { /etc/init.d/mmpbxd disable; /etc/init.d/mmpbxfwctl disable; /etc/init.d/mmpbxd stop; /etc/init.d/mmpbxfwctl stop; uci -q set web.card_telephony.hide='1'; SRV_nginx=$(( $SRV_nginx + 1 )); } > /dev/null 2>&1
+  [ "$NFC" = "0" ] && { /etc/init.d/nfcd disable; /etc/init.d/nfcd stop; uci -q set web.card_nfc.hide='1'; SRV_nginx=$(( $SRV_nginx + 1 )); } > /dev/null 2>&1
   [ "$MULTIAP" = "0" -a $SRV_multiap -ge 0 ] && { /etc/init.d/multiap_controller disable; /etc/init.d/multiap_agent disable; /etc/init.d/multiap_vendorextensions disable; /etc/init.d/multiap_controller stop; /etc/init.d/multiap_agent stop; /etc/init.d/multiap_vendorextensions stop; uci -q set web.card_wireless_boosters.card.hide='1'; SRV_nginx=$(( $SRV_nginx + 1 )); } > /dev/null 2>&1
   [ "$PRNTR" = "0" ] && { /etc/init.d/cupsd disable; /etc/init.d/cupsd stop; } > /dev/null 2>&1
   [ "$SAMBA" = "0" -a -e /etc/init.d/samba ] && { /etc/init.d/samba disable; /etc/init.d/samba stop; SRV_cs=$(( $SRV_cs + 1 )); } > /dev/null 2>&1
