Added WAN Supervision and fixed SAMBA service

diff --git a/utilities/de-telstra b/utilities/de-telstra
--- a/utilities/de-telstra
+++ b/utilities/de-telstra
@@ -22,11 +22,12 @@ Options:
           k            - Keep default public authorized keys
           m            - Keep Telstra monitoring and data collection enabled
           n            - Keep Telstra NTP servers
+          s            - Keep WAN Supervision as BFD
           x            - Keep noexec on ext2/3/4, fat, hfsplus, hfsplusjournal
                           and ntfs filesystems (i.e. prevent execution of
                           scripts/programs on USB devices)
           T            - Keep all default Telstra configuration (Equivalent
-                          to: -ka -kc -kk -km -kn -kx)
+                          to: -ka -kc -kk -km -kn -ks -kx)
  -h u|d|s|<hostname>
     where u            Leave hostname unchanged
           d            Set the hostname to $VARIANT
@@ -47,28 +48,29 @@ Options:
                         IPv4 addresses (e.g. 8.8.8.8,1.1.1.1)
  -a u|y|n              WAN ALG NAT Helpers:     u=Unchanged y=Enable n=Disable
  -c u|y|n              Content Sharing:         u=unchanged y=Enable n=Disable
- -f u|y|n              File Sharing:            u=unchanged y=Enable n=Disable
- -p u|y|n|d          ! Power Saving:            u=unchanged y=Enable n=Disable d=Default
- -r u|y|n              Printer Sharing:         u=unchanged y=Enable n=Disable
- -t u|y|n              Telephony:               u=unchanged y=Enable n=Disable
  -e u|y|n              DECT Emission Mode:      u=unchanged y=Enable n=Disable
- -u u|y|n              UPnP Service:            u=unchanged y=Enable n=Disable
- -m u|y|n            * MultiAP (EasyMesh):      u=unchanged y=Enable n=Disable
+ -f u|y|n              File Sharing:            u=unchanged y=Enable n=Disable
  -g u|y|n            * DumaOS (Game Optimiser): u=unchanged y=Enable n=Disable
+ -m u|y|n            * MultiAP (EasyMesh):      u=unchanged y=Enable n=Disable
+ -p u|y|n|d          ! Power Saving:            u=unchanged y=Enable n=Disable d=Default
  -q u|y|n            * NFC:                     u=unchanged y=Enable n=Disable
+ -r u|y|n              Printer Sharing:         u=unchanged y=Enable n=Disable
+ -s u|b|d|n            WAN Supervision:         u=unchanged b=BFD d=DNS n=Disable 
+ -t u|y|n              Telephony:               u=unchanged y=Enable n=Disable
+ -u u|y|n              UPnP Service:            u=unchanged y=Enable n=Disable
  -w u|y|n              WPS:                     u=unchanged y=Enable n=Disable
                          (on non-Guest and non-Backhaul SSIDs)
  -F u|y|n              RTFD root protection:    u=unchanged y=Enable n=Disable
                         NOTE: tch-gui-unhide will ALWAYS enable RTFD protection
- -A                    Equivalent to: -hd -dg -an -cn -fn -rn -un -wn -Fy
- -S                    Equivalent to: -hs -dg -an -cn -fn -rn -un -wn -Fy
+ -A                    Equivalent to: -hd -dg -an -cn -fn -rn -sd -un -wn -Fy
+ -S                    Equivalent to: -hs -dg -an -cn -fn -rn -sd -un -wn -Fy
  -M                    Minimum memory mode: Equivalent to:
                               -an -cn -fn -rn -tn -en -un -mn -gn -qn -Fy
                         PLUS stops and disables the associated services
  -G                    Removes the Guest Wi-Fi SSIDs, firewall rules/zones, and
                         guest networks
  -R                    Reset to device defaults: Equivalent to:
-                        -hmymodem -dmodem -na -ay -cy -fy -pd -ry -ty -ey -uy -my -gy -qy -wy -Fn
+                        -hmymodem -dmodem -na -ay -cy -fy -pd -ry -ty -ey -uy -my -gy -qy -wy -Fn -sb
  -o                    Configures opkg
  -U                    Download the latest version of $SCRIPT from GitHub
 
@@ -121,6 +123,7 @@ SRV_network=0
 SRV_ntp=0
 SRV_qos=0
 SRV_samba=0
+SRV_supervision=0
 SRV_system=0
 SRV_watchdog=0
 SRV_nginx=0
@@ -166,6 +169,7 @@ POWER='u'
 PRNTR='u'
 ROOT_PROTECT='u'
 SAMBA='u'
+SUPERVISION='u'
 UPNP='u'
 WPS='u'
 # Overrides
@@ -176,7 +180,7 @@ MONITORING='n'
 NTP='n'
 NOEXEC='n'
 
-while getopts :a:c:d:e:f:g:h:k:m:n:op:q:r:t:u:w:AF:GMRSU option
+while getopts :a:c:d:e:f:g:h:k:m:n:op:q:r:s:t:u:w:AF:GMRSU option
 do
  case "${option}" in
   a)  case "${OPTARG}" in y) ALG='1';; n) ALG='0';; u) ALG='u';; *) ALG='u'; echo 'ERROR: -a valid options are y, n, or u'; exit 1;; esac;;
@@ -186,22 +190,23 @@ do
   f)  case "${OPTARG}" in y) SAMBA='1';; n) SAMBA='0';; u) SAMBA='u';; *) SAMBA='u'; echo 'ERROR: -f valid options are y, n, or u'; exit 1;; esac;;
   g)  case "${OPTARG}" in y) DUMAOS='1';; n) DUMAOS='0';; u) DUMAOS='u';; *) DUMAOS='u'; echo 'ERROR: -g valid options are y, n, or u'; exit 1;; esac;;
   h)  HOST=${OPTARG};;
-  k)  case "${OPTARG}" in k) KEYS='y';; c) CWMP='y';; m) MONITORING='y';; a) AIR='y';; n) NTP='y';; x) NOEXEC='y';; T) KEYS='y'; CWMP='y'; MONITORING='y'; AIR='y'; NTP='y'; NOEXEC='y';; *) echo "ERROR: Unknown override option $OPTARG"; exit 1;; esac;;
+  k)  case "${OPTARG}" in k) KEYS='y';; c) CWMP='y';; m) MONITORING='y';; a) AIR='y';; n) NTP='y';; s) SUPERVISION='BFD';; x) NOEXEC='y';; T) KEYS='y'; CWMP='y'; MONITORING='y'; AIR='y'; NTP='y'; SUPERVISION='BFD'; NOEXEC='y';; *) echo "ERROR: Unknown override option $OPTARG"; exit 1;; esac;;
   m)  case "${OPTARG}" in y) MULTIAP='1';; n) MULTIAP='0';; u) MULTIAP='u';; *) MULTIAP='u'; echo 'ERROR: -m valid options are y, n, or u'; exit 1;; esac;;
   n)  NS=${OPTARG};;
   o)  OPKG='y';;
   p)  case "${OPTARG}" in y) POWER='y';; n) POWER='n';; u) POWER='u';; d) POWER='d';; *) POWER='u'; echo 'ERROR: -p valid options are y, n, u or d'; exit 1;; esac;;
   q)  case "${OPTARG}" in y) NFC='1';; n) NFC='0';; u) NFC='u';; *) NFC='u'; echo 'ERROR: -q valid options are y, n, or u'; exit 1;; esac;;
   r)  case "${OPTARG}" in y) PRNTR='1';; n) PRNTR='0';; u) PRNTR='u';; *) PRNTR='u'; echo 'ERROR: -r valid options are y, n, or u'; exit 1;; esac;;
+  s)  case "${OPTARG}" in d) SUPERVISION='BFD';; d) SUPERVISION='DNS';; n) SUPERVISION='Disabled';; u) SUPERVISION='u';; *) SUPERVISION='u'; echo 'ERROR: -s valid options are b, d, n, or u'; exit 1;; esac;;
   t)  case "${OPTARG}" in y) MMPBX='1';; n) MMPBX='0';; u) MMPBX='u';; *) MMPBX='u'; echo 'ERROR: -t valid options are y, n, or u'; exit 1;; esac;;
   u)  case "${OPTARG}" in y) UPNP='1';; n) UPNP='0';; u) UPNP='u';; *) UPNP='u'; echo 'ERROR: -u valid options are y, n, or u'; exit 1;; esac;;
   w)  case "${OPTARG}" in y) WPS='1';; n) WPS='0';; u) WPS='u';; *) WPS='u'; echo 'ERROR: -w valid options are y, n, or u'; exit 1;; esac;;
-  A)  HOST='d'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1';;
+  A)  HOST='d'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1'; SUPERVISION='DNS';;
   F)  case "${OPTARG}" in y) ROOT_PROTECT='1';; n) ROOT_PROTECT='0';; u) ROOT_PROTECT='u';; *) ROOT_PROTECT='u'; echo 'ERROR: -F valid options are y, n, or u'; exit 1;; esac;;
   G)  GUEST='n';;
   M)  LITE='y'; ALG='0'; DECT='0'; DLNAD='0'; DUMAOS='0'; MMPBX='0'; MULTIAP='0'; NFC='0'; PRNTR='0'; SAMBA='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1';;
-  R)  LITE='R'; HOST='mymodem'; DOMAIN='modem'; NS='a'; ALG='1'; DLNAD='1'; DUMAOS='0'; SAMBA='1'; MULTIAP='1'; POWER='d'; PRNTR='1'; MMPBX='1'; DECT='1'; UPNP='1'; ROOT_PROTECT='0'; NFC='y';;
-  S)  HOST='s'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1';;
+  R)  LITE='R'; HOST='mymodem'; DOMAIN='modem'; NS='a'; ALG='1'; DLNAD='1'; DUMAOS='0'; SAMBA='1'; MULTIAP='1'; POWER='d'; PRNTR='1'; MMPBX='1'; DECT='1'; UPNP='1'; ROOT_PROTECT='0'; NFC='y'; SUPERVISION='BFD';;
+  S)  HOST='s'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='1'; SUPERVISION='DNS';;
   U)  upgrade;;
   ?)  usage;;
  esac
@@ -574,18 +579,18 @@ if [ $? -eq 0 ]; then
         IPv4PATTERN="([^.]|^)([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5]).([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5]).([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5]).([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])([^.]|$)"
         echo "$WANDNS1" | grep -q -E $IPv4PATTERN
         if [ $? -eq 1 ]; then
-          echo [$SCRIPT]: WARNING! Invalid IP address $WANDNS1 IGNORED
+          echo -e "[$SCRIPT]: \033[1;31mWARNING! Invalid IP address $WANDNS1 IGNORED\033[0m"
           WANDNS1=""
         fi
         if [ ! -z "$WANDNS2" ]; then
           echo "$WANDNS2" | grep -q -E $IPv4PATTERN
           if [ $? -eq 1 ]; then
-            echo [$SCRIPT]: WARNING! Invalid IP address $WANDNS2 IGNORED
+            echo -e "[$SCRIPT]: \033[1;31mWARNING! Invalid IP address $WANDNS2 IGNORED\033[0m"
             WANDNS2=""
           fi
         fi
         if [ -z "$WANDNS1" -a -z "$WANDNS2" ]; then
-          echo [$SCRIPT]: WARNING! No valid IP addresses specified - No DNS Server changes applied
+          echo -e "[$SCRIPT]: \033[1;31mWARNING! No valid IP addresses specified - No DNS Server changes applied\033[0m"
         else
           if [ "$PEERDNS_NOW" = "0" ]; then
             echo [$SCRIPT]: ISP peer DNS unchanged \[$(status2text $PEERDNS_NOW)\]
@@ -644,6 +649,7 @@ else
   uci set printersharing.config.enabled="$PRNTR"
   uci commit printersharing
   SRV_cups=$(( $SRV_cups + 1 ))
+  PS_NOW="$PRNTR"
   echo [$SCRIPT]: Printer sharing $(status2text $PRNTR)
 fi
 
@@ -654,6 +660,7 @@ else
   uci set samba.samba.filesharing="$SAMBA"
   uci commit samba
   SRV_samba=$(( $SRV_samba + 1 ))
+  FS_NOW="$SAMBA"
   echo [$SCRIPT]: File sharing $(status2text $SAMBA)
 fi
 
@@ -710,6 +717,16 @@ else
   uci commit mmpbx
   SRV_mmpbxd=$(( $SRV_mmpbxd + 1 ))
   echo [$SCRIPT]: DECT Emission Mode $(status2text $DECT)
+fi
+
+SUPERVISION_NOW="$(uci -q get supervision.global.enabled)"
+if [ "$SUPERVISION" = "u" -o "$SUPERVISION_NOW" = "$SUPERVISION" ]; then
+  echo [$SCRIPT]: WAN Supervision unchanged \[$SUPERVISION_NOW\]
+else
+  uci set supervision.global.enabled="$SUPERVISION"
+  uci commit supervision
+  SRV_supervision=$(( $SRV_supervision + 1 ))
+  echo [$SCRIPT]: WAN Supervision Mode = $SUPERVISION
 fi
 
 if [ "$WPS" = "u" ]; then
@@ -976,7 +993,7 @@ if [ "$OPKG" = "y" -o $OPKG_DEP -gt 0 ]; then
           echo [$SCRIPT]: Updating local package list
           opkg update | logger -s -t rpc.gui.opkg -p user.info;
         else
-          echo [$SCRIPT]: WARNING: No internet connection??? opkg not configured...
+          echo -e "[$SCRIPT]: \033[1;31mWARNING! No internet connection??? opkg not configured...\033[0m"
         fi
       else
         echo [$SCRIPT]: Sorry!! I do not know how to configure opkg for Firmware Version $(uci get version.@version[0].marketing_version)
@@ -1070,6 +1087,7 @@ echo [$SCRIPT]: Applying required service changes...
 [ $SRV_ntp -gt 0 ] && /etc/init.d/sysntpd restart > /dev/null 2>&1
 [ $SRV_samba -gt 0 ] && { /etc/init.d/samba enable; /etc/init.d/samba reload; } > /dev/null 2>&1
 [ $SRV_samba -gt 0 -a -e /etc/init.d/samba-nmbd ] && { /etc/init.d/samba-nmbd enable; /etc/init.d/samba-nmbd reload; } > /dev/null 2>&1
+[ $SRV_supervision -gt 0 ] && /etc/init.d/supervision reload > /dev/null 2>&1
 [ $SRV_system -gt 0 ] && /etc/init.d/system reload > /dev/null 2>&1
 [ $SRV_upnp -gt 0 ] && { /etc/init.d/miniupnpd-tch enable; /etc/init.d/miniupnpd-tch restart; } > /dev/null 2>&1
 [ $SRV_hostapd -gt 0 ] && { /etc/init.d/hostapd reload && ubus send config "{'reload':'wireless'}"; } > /dev/null 2>&1
