Disable/enable the intercept daemon

diff --git a/utilities/de-telstra b/utilities/de-telstra
--- a/utilities/de-telstra
+++ b/utilities/de-telstra
@@ -54,6 +54,7 @@ Options:
  -e u|y|n              DECT Emission Mode:      u=unchanged y=Enable n=Disable
  -f u|y|n              File Sharing:            u=unchanged y=Enable n=Disable
  -g u|y|n            * DumaOS (Game Optimiser): u=unchanged y=Enable n=Disable
+ -i u|y|n              Intercept Daemon:        u=unchanged y=Enable n=Disable
  -m u|y|n            * MultiAP (EasyMesh):      u=unchanged y=Enable n=Disable
  -p u|y|n|d          ! Power Saving:            u=unchanged y=Enable n=Disable d=Default
  -q u|y|n            * NFC:                     u=unchanged y=Enable n=Disable
@@ -65,14 +66,14 @@ Options:
                          (on non-Guest and non-Backhaul SSIDs)
  -F u|y|n              RTFD root protection:    u=unchanged y=Enable n=Disable
                          NOTE: tch-gui-unhide will ALWAYS enable RTFD protection
- -A                    Equivalent to: -hd -dg -an -cn -fn -rn -sd -un -wn -Fy
- -S                    Equivalent to: -hs -dg -an -cn -fn -rn -sd -un -wn -Fy
+ -A                    Equivalent to: -hd -dg -an -cn -fn -in -rn -sd -un -wn -Fy
+ -S                    Equivalent to: -hs -dg -an -cn -fn -in -rn -sd -un -wn -Fy
  -M                    Minimum memory mode: Equivalent to:
-                           -an -cn -fn -rn -tn -en -un -mn -gn -qn -Fy
+                           -an -cn -fn -in -rn -tn -en -un -mn -gn -qn -Fy
                          PLUS stops and disables the associated services
  -G                    Removes the Guest Wi-Fi SSIDs, firewall rules/zones, and guest networks
  -R                    Reset to device defaults: Equivalent to:
-                         -hmymodem -dmodem -na -ay -cy -fy -pd -ry -ty -ey -uy -my -gy -qy -wy -Fn -sb
+                         -hmymodem -dmodem -na -ay -cy -fy -iy -pd -ry -ty -ey -uy -my -gy -qy -wy -Fn -sb
  -o                    Configures opkg
  -O 17|18|19           Overrides the default opkg repository with the specified version
  -U                    Download the latest version of $SCRIPT from GitHub
@@ -126,6 +127,7 @@ set_defaults() {
   __DUMAOS='u'
   __GUEST='n'
   __HOST='u'
+  __INTERCEPT='u'
   __LITE='n'
   __MMPBX='u'
   __MULTIAP='u'
@@ -162,7 +164,7 @@ RESTART_SERVICES=y
 SAVE_DEFAULTS=n
 SHOW_DEFAULTS=n
 
-while getopts :a:b:c:d:e:f:g:h:k:m:n:op:q:r:s:t:u:w:yAF:GMO:RSU-: option; do
+while getopts :a:b:c:d:e:f:g:h:i:k:m:n:op:q:r:s:t:u:w:yAF:GMO:RSU-: option; do
  case "${option}" in
   -)  case "${OPTARG}" in
         no-defaults) set_defaults;;
@@ -172,33 +174,34 @@ while getopts :a:b:c:d:e:f:g:h:k:m:n:op:q:r:s:t:u:w:yAF:GMO:RSU-: option; do
         no-service-restart) RESTART_SERVICES=n;;
         *) usage --$OPTARG;;
       esac;;
-  a)  case "${OPTARG}" in y) __ALG='1';; n) __ALG='0';; u) __ALG='u';; *) __ALG='u'; echo 'ERROR: -a valid options are y, n, or u'; exit 1;; esac;;
+  a)  case "${OPTARG}" in y) __ALG='1';; n) __ALG='0';; u) __ALG='u';; *) echo 'ERROR: -a valid options are y, n, or u'; exit 1;; esac;;
   b)  echo 'WARNING: -b option deprecated. Use -a instead!'; exit 1;;
-  c)  case "${OPTARG}" in y) __DLNAD='1';; n) __DLNAD='0';; u) __DLNAD='u';; *) __DLNAD='u'; echo 'ERROR: -c valid options are y, n, or u'; exit 1;; esac;;
+  c)  case "${OPTARG}" in y) __DLNAD='1';; n) __DLNAD='0';; u) __DLNAD='u';; *) echo 'ERROR: -c valid options are y, n, or u'; exit 1;; esac;;
   d)  case "${OPTARG}" in g|G) __DOMAIN='gateway';; l|L) __DOMAIN='lan';; u) __DOMAIN='u';; *) __DOMAIN="${OPTARG}";; esac;;
-  e)  case "${OPTARG}" in y) __DECT='1';; n) __DECT='0';; u) __DECT='u';; *) __DECT='u'; echo 'ERROR: -e valid options are y, n, or u'; exit 1;; esac;;
-  f)  case "${OPTARG}" in y) __SAMBA='1';; n) __SAMBA='0';; u) __SAMBA='u';; *) __SAMBA='u'; echo 'ERROR: -f valid options are y, n, or u'; exit 1;; esac;;
-  g)  case "${OPTARG}" in y) __DUMAOS='1';; n) __DUMAOS='0';; u) __DUMAOS='u';; *) __DUMAOS='u'; echo 'ERROR: -g valid options are y, n, or u'; exit 1;; esac;;
+  e)  case "${OPTARG}" in y) __DECT='1';; n) __DECT='0';; u) __DECT='u';; *) echo 'ERROR: -e valid options are y, n, or u'; exit 1;; esac;;
+  f)  case "${OPTARG}" in y) __SAMBA='1';; n) __SAMBA='0';; u) __SAMBA='u';; *) echo 'ERROR: -f valid options are y, n, or u'; exit 1;; esac;;
+  g)  case "${OPTARG}" in y) __DUMAOS='1';; n) __DUMAOS='0';; u) __DUMAOS='u';; *) echo 'ERROR: -g valid options are y, n, or u'; exit 1;; esac;;
   h)  __HOST=${OPTARG};;
+  i)  case "${OPTARG}" in y) __INTERCEPT='1';; n) __INTERCEPT='0';; u) __INTERCEPT='u';; *) echo 'ERROR: -i valid options are y, n, or u'; exit 1;; esac;;
   k)  case "${OPTARG}" in a) __AIR='y';; c) __CWMP='y';; k) __KEYS='y';; l) __LTE='y';; m) __MONITORING='y';; n) __NTP='y';; q) __QoS='y';; s) __SUPERVISION='BFD';; x) __NOEXEC='y';; T) __LTE='y'; __KEYS='y'; __CWMP='y'; __MONITORING='y'; __AIR='y'; __NTP='y'; __QoS='y'; __SUPERVISION='BFD'; __NOEXEC='y';; *) echo "ERROR: Unknown override option $OPTARG"; exit 1;; esac;;
-  m)  case "${OPTARG}" in y) __MULTIAP='1';; n) __MULTIAP='0';; u) __MULTIAP='u';; *) __MULTIAP='u'; echo 'ERROR: -m valid options are y, n, or u'; exit 1;; esac;;
+  m)  case "${OPTARG}" in y) __MULTIAP='1';; n) __MULTIAP='0';; u) __MULTIAP='u';; *) echo 'ERROR: -m valid options are y, n, or u'; exit 1;; esac;;
   n)  __NS=${OPTARG};;
   o)  __OPKG='y';;
-  p)  case "${OPTARG}" in y) __POWER='y';; n) __POWER='n';; u) __POWER='u';; d) __POWER='d';; *) __POWER='u'; echo 'ERROR: -p valid options are y, n, u or d'; exit 1;; esac;;
-  q)  case "${OPTARG}" in y) __NFC='1';; n) __NFC='0';; u) __NFC='u';; *) __NFC='u'; echo 'ERROR: -q valid options are y, n, or u'; exit 1;; esac;;
-  r)  case "${OPTARG}" in y) __PRNTR='1';; n) __PRNTR='0';; u) __PRNTR='u';; *) __PRNTR='u'; echo 'ERROR: -r valid options are y, n, or u'; exit 1;; esac;;
-  s)  case "${OPTARG}" in b|B) __SUPERVISION='BFD';; d|D) __SUPERVISION='DNS';; n) __SUPERVISION='Disabled';; u) __SUPERVISION='u';; *) __SUPERVISION='u'; echo 'ERROR: -s valid options are b, d, n, or u'; exit 1;; esac;;
-  t)  case "${OPTARG}" in y) __MMPBX='1';; n) __MMPBX='0';; u) __MMPBX='u';; *) __MMPBX='u'; echo 'ERROR: -t valid options are y, n, or u'; exit 1;; esac;;
-  u)  case "${OPTARG}" in y) __UPNP='1';; n) __UPNP='0';; u) __UPNP='u';; *) __UPNP='u'; echo 'ERROR: -u valid options are y, n, or u'; exit 1;; esac;;
-  w)  case "${OPTARG}" in y) __WPS='1';; n) __WPS='0';; u) __WPS='u';; *) __WPS='u'; echo 'ERROR: -w valid options are y, n, or u'; exit 1;; esac;;
+  p)  case "${OPTARG}" in y) __POWER='y';; n) __POWER='n';; u) __POWER='u';; d) __POWER='d';; *) echo 'ERROR: -p valid options are y, n, u or d'; exit 1;; esac;;
+  q)  case "${OPTARG}" in y) __NFC='1';; n) __NFC='0';; u) __NFC='u';; *) echo 'ERROR: -q valid options are y, n, or u'; exit 1;; esac;;
+  r)  case "${OPTARG}" in y) __PRNTR='1';; n) __PRNTR='0';; u) __PRNTR='u';; *) echo 'ERROR: -r valid options are y, n, or u'; exit 1;; esac;;
+  s)  case "${OPTARG}" in b|B) __SUPERVISION='BFD';; d|D) __SUPERVISION='DNS';; n) __SUPERVISION='Disabled';; u) __SUPERVISION='u';; *) echo 'ERROR: -s valid options are b, d, n, or u'; exit 1;; esac;;
+  t)  case "${OPTARG}" in y) __MMPBX='1';; n) __MMPBX='0';; u) __MMPBX='u';; *) echo 'ERROR: -t valid options are y, n, or u'; exit 1;; esac;;
+  u)  case "${OPTARG}" in y) __UPNP='1';; n) __UPNP='0';; u) __UPNP='u';; *) echo 'ERROR: -u valid options are y, n, or u'; exit 1;; esac;;
+  w)  case "${OPTARG}" in y) __WPS='1';; n) __WPS='0';; u) __WPS='u';; *) echo 'ERROR: -w valid options are y, n, or u'; exit 1;; esac;;
   y)  __YES='y';;
-  A)  __HOST='d'; __DOMAIN='gateway'; __ALG='0'; __DLNAD='0'; __SAMBA='0'; __PRNTR='0'; __UPNP='0'; __WPS='0'; __ROOT_PROTECT='1'; __SUPERVISION='DNS';;
-  F)  case "${OPTARG}" in y) __ROOT_PROTECT='1';; n) __ROOT_PROTECT='0';; u) __ROOT_PROTECT='u';; *) __ROOT_PROTECT='u'; echo 'ERROR: -F valid options are y, n, or u'; exit 1;; esac;;
+  A)  __HOST='d'; __DOMAIN='gateway'; __ALG='0'; __DLNAD='0'; __SAMBA='0'; __PRNTR='0'; __UPNP='0'; __WPS='0'; __ROOT_PROTECT='1'; __SUPERVISION='DNS'; __INTERCEPT='0';;
+  F)  case "${OPTARG}" in y) __ROOT_PROTECT='1';; n) __ROOT_PROTECT='0';; u) __ROOT_PROTECT='u';; *) echo 'ERROR: -F valid options are y, n, or u'; exit 1;; esac;;
   G)  __GUEST='y';;
-  M)  __LITE='y'; __ALG='0'; __DECT='0'; __DLNAD='0'; __DUMAOS='0'; __MMPBX='0'; __MULTIAP='0'; __NFC='0'; __PRNTR='0'; __SAMBA='0'; __UPNP='0'; __WPS='0'; __ROOT_PROTECT='1';;
+  M)  __LITE='y'; __ALG='0'; __DECT='0'; __DLNAD='0'; __DUMAOS='0'; __INTERCEPT='0' __MMPBX='0'; __MULTIAP='0'; __NFC='0'; __PRNTR='0'; __SAMBA='0'; __UPNP='0'; __WPS='0'; __ROOT_PROTECT='1';;
   O)  case "${OPTARG}" in 17|18|19) __REPO=$OPTARG;; *) echo 'ERROR: -O valid options are 17, 18 or 19'; exit 1;; esac;;
-  R)  __LITE='R'; __HOST='mymodem'; __DOMAIN='modem'; __NS='a'; __ALG='1'; __DLNAD='1'; __DUMAOS='0'; __SAMBA='1'; __MULTIAP='1'; __POWER='d'; __PRNTR='1'; __MMPBX='1'; __DECT='1'; __UPNP='1'; __ROOT_PROTECT='0'; __NFC='y'; __SUPERVISION='BFD';;
-  S)  __HOST='s'; __DOMAIN='gateway'; __ALG='0'; __DLNAD='0'; __SAMBA='0'; __PRNTR='0'; __UPNP='0'; __WPS='0'; __ROOT_PROTECT='1'; __SUPERVISION='DNS';;
+  R)  __LITE='R'; __HOST='mymodem'; __DOMAIN='modem'; __NS='a'; __ALG='1'; __DLNAD='1'; __DUMAOS='0'; __SAMBA='1'; __MULTIAP='1'; __POWER='d'; __PRNTR='1'; __MMPBX='1'; __DECT='1'; __UPNP='1'; __ROOT_PROTECT='0'; __NFC='y'; __SUPERVISION='BFD'; __INTERCEPT='1';;
+  S)  __HOST='s'; __DOMAIN='gateway'; __ALG='0'; __DLNAD='0'; __SAMBA='0'; __PRNTR='0'; __UPNP='0'; __WPS='0'; __ROOT_PROTECT='1'; __SUPERVISION='DNS'; __INTERCEPT='0';;
   U)  upgrade;;
   ?)  usage;;
   *)  usage -$OPTARG;;
@@ -221,6 +224,7 @@ SRV_fw=0
 SRV_hostapd=0
 SRV_hotspot=0
 SRV_iqos=0
+SRV_intercept=0
 SRV_mmpbxd=0
 SRV_mobiled=0
 SRV_monitor=0
@@ -316,6 +320,7 @@ if [ $SAVE_DEFAULTS = y -o $SHOW_DEFAULTS = y -o $__YES = n ]; then
   show_default "e"  "DECT Emission Mode" $__DECT
   show_default "f"  "File Sharing" $__SAMBA
   [ $SRV_dumaos -ge 0 ] && show_default "g"  "DumaOS (Game Optimiser)" $__DUMAOS
+  show_default "i"  "Intercept Daemon" $__INTERCEPT
   [ $SRV_multiap -ge 0 ] && show_default "m"  "MultiAP (EasyMesh)" $__MULTIAP
   show_default "p"  "Power Saving" $__POWER
   [ $SRV_nfc -ge 0 ] && show_default "q"  "NFC" $__NFC
@@ -941,6 +946,16 @@ if [ $SRV_supervision -ge 0 ]; then
   fi
 fi
 
+INTERCEPT_NOW="$(uci -q get intercept.config.enabled)"
+if [ "$__INTERCEPT" = "u" -o "$INTERCEPT_NOW" = "$__INTERCEPT" ]; then
+  echo [$SCRIPT]: Intercept Daemon unchanged \[$(status2text $INTERCEPT_NOW)\]
+else
+  uci set intercept.config.enabled="$__DECT"
+  uci commit intercept
+  SRV_intercept=$(( $SRV_intercept + 1 ))
+  echo [$SCRIPT]: Intercept Daemon $(status2text $__DECT)
+fi
+
 if [ "$__WPS" = "u" ]; then
   WPS_NOW="$(uci show wireless | grep wps_state=\'1\' | wc -l)"
   if [ "$WPS_NOW" -eq 1 ]; then
@@ -1327,6 +1342,7 @@ echo [$SCRIPT]: Applying service changes...
 [ $SRV_cwmp -gt 0 -a -e /etc/init.d/cwmpd ] && { /etc/init.d/cwmpd disable; /etc/init.d/cwmpd stop; } > /dev/null 2>&1
 [ $SRV_dumaos -gt 0 ] && /etc/init.d/dumaos enable > /dev/null 2>&1
 [ $SRV_hotspot -gt 0 -a -e /etc/init.d/hotspotd ] && { /etc/init.d/hotspotd disable; /etc/init.d/hotspotd stop; } > /dev/null 2>&1
+[ $SRV_intercept -gt 0 ] && /etc/init.d/intercept enable > /dev/null 2>&1
 [ $SRV_mmpbxd -gt 0 ] && { /etc/init.d/mmpbxd enable; /etc/init.d/mmpbxfwctl enable; } > /dev/null 2>&1
 [ $SRV_monitor -gt 0 -a -e /etc/init.d/autoreset ] && { /etc/init.d/autoreset disable; /etc/init.d/autoreset stop; } > /dev/null 2>&1
 [ $SRV_monitor -gt 0 -a -e /etc/init.d/tls-thor ] && { /etc/init.d/tls-thor disable; /etc/init.d/tls-thor stop; } > /dev/null 2>&1
@@ -1346,6 +1362,7 @@ else
   [ $SRV_dropbear -gt 0 ] && /etc/init.d/dropbear reload > /dev/null 2>&1
   [ $SRV_dumaos -gt 0 ] && /etc/init.d/dumaos restart > /dev/null 2>&1
   [ $SRV_iqos -gt 0 ] && /etc/init.d/iqos restart > /dev/null 2>&1
+  [ $SRV_intercept -gt 0 ] && /etc/init.d/intercept restart > /dev/null 2>&1
   [ $SRV_mmpbxd -gt 0 ] && { /etc/init.d/mmpbxd restart; /etc/init.d/mmpbxfwctl restart; } > /dev/null 2>&1
   [ $SRV_mobiled -gt 0 ] && /etc/init.d/mobiled restart > /dev/null 2>&1
   [ $SRV_monitor -gt 0 -a -e /etc/init.d/wifi-doctor-agent ] && /etc/init.d/wifi-doctor-agent reload > /dev/null 2>&1
@@ -1377,6 +1394,7 @@ if [ "$__LITE" = 'y' ]; then
   [ "$__DLNAD" = "0" ] && { /etc/init.d/dlnad disable; /etc/init.d/dlnad stop; /etc/init.d/mud disable; /etc/init.d/mud stop; } > /dev/null 2>&1
   [ "$__DUMAOS" = "0" -a $SRV_dumaos -ge 0 ] && { /etc/init.d/dumaos disable; /etc/init.d/ndhttpd disable; /etc/init.d/dumaos stop; /etc/init.d/ndhttpd stop; } > /dev/null 2>&1
   [ "$__DUMAOS" = "0" -a $SRV_dumaos -ge 0 -a -e /etc/init.d/telemetry-daemon ] && { /etc/init.d/telemetry-daemon disable; /etc/init.d/telemetry-daemon stop; } > /dev/null 2>&1
+  [ "$__INTERCEPT" = "0" ] && { /etc/init.d/intercept disable; /etc/init.d/intercept stop; } > /dev/null 2>&1
   [ "$__MMPBX" = "0" ] && { /etc/init.d/mmpbxd disable; /etc/init.d/mmpbxfwctl disable; /etc/init.d/mmpbxd stop; /etc/init.d/mmpbxfwctl stop; } > /dev/null 2>&1
   [ "$__NFC" = "0" ] && { /etc/init.d/nfcd disable; /etc/init.d/nfcd stop; } > /dev/null 2>&1
   [ "$__MULTIAP" = "0" -a $SRV_multiap -ge 0 ] && { /etc/init.d/multiap_controller disable; /etc/init.d/multiap_agent disable; /etc/init.d/multiap_vendorextensions disable; /etc/init.d/multiap_controller stop; /etc/init.d/multiap_agent stop; /etc/init.d/multiap_vendorextensions stop; } > /dev/null 2>&1
