Prevent root loss on RTFD from GUI or rtfd --soft

diff --git a/utilities/de-telstra b/utilities/de-telstra
--- a/utilities/de-telstra
+++ b/utilities/de-telstra
@@ -52,12 +52,13 @@ Options:
  -m u|y|n            * MultiAP (EasyMesh):      u=unchanged y=Enable n=Disable
  -g u|y|n            * DumaOS (Game Optimiser): u=unchanged y=Enable n=Disable
  -w u|y|n              WPS on non-Guest and non-Backhaul SSIDs: u=unchanged y=Enable n=Disable
- -A                    Equivalent to: -hd -dg -an -cn -fn -rn -un -wn
- -S                    Equivalent to: -hs -dg -an -cn -fn -rn -un -wn
- -M                    Minimum memory mode: Equivalent to: -an -cn -fn -rn -tn -en -un -mn -gn
+ -F u|y|n              Factory reset root protection: u=unchanged y=Enable n=Disable
+ -A                    Equivalent to: -hd -dg -an -cn -fn -rn -un -wn -Fy
+ -S                    Equivalent to: -hs -dg -an -cn -fn -rn -un -wn -Fy
+ -M                    Minimum memory mode: Equivalent to: -an -cn -fn -rn -tn -en -un -mn -gn -Fy
                         PLUS stops and disables the associated services
  -R                    Reset to device defaults
-                        (equivalent to: -hmymodem -dmodem -na -ay -cy -fy -py -ry -ty -ey -uy -my -gy -wy)
+                        (equivalent to: -hmymodem -dmodem -na -ay -cy -fy -py -ry -ty -ey -uy -my -gy -wy -Fn)
  -o                    Configures opkg
  -U                    Check for and download the latest version from GitHub
 
@@ -169,6 +170,7 @@ NS='u'
 OPKG='n'
 POWER='u' 
 PRNTR='u'
+ROOT_PROTECT='u'
 SAMBA='u'
 UPNP='u'
 WPS='u'
@@ -179,7 +181,7 @@ KEYS='n'
 MONITORING='n'
 NTP='n'
 
-while getopts :a:c:d:e:f:g:h:k:m:n:op:r:t:u:w:AMRSU option
+while getopts :a:c:d:e:f:g:h:k:m:n:op:r:t:u:w:AF:MRSU option
 do
  case "${option}" in
   a)  case "${OPTARG}" in y) ALG='1';; n) ALG='0';; u) ALG='u';; *) ALG='u'; echo 'ERROR: -a valid options are y, n, or u'; exit 1;; esac;;
@@ -198,10 +200,11 @@ do
   t)  case "${OPTARG}" in y) MMPBX='1';; n) MMPBX='0';; u) MMPBX='u';; *) MMPBX='u'; echo 'ERROR: -t valid options are y, n, or u'; exit 1;; esac;;
   u)  case "${OPTARG}" in y) UPNP='1';; n) UPNP='0';; u) UPNP='u';; *) UPNP='u'; echo 'ERROR: -u valid options are y, n, or u'; exit 1;; esac;;
   w)  case "${OPTARG}" in y) WPS='1';; n) WPS='0';; u) WPS='u';; *) WPS='u'; echo 'ERROR: -w valid options are y, n, or u'; exit 1;; esac;;
-  A)  HOST='d'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0';;
-  M)  LITE='y'; ALG='0'; DECT='0'; DLNAD='0'; DUMAOS='0'; MMPBX='0'; MULTIAP='0'; PRNTR='0'; SAMBA='0'; UPNP='0'; WPS='0';;
-  R)  LITE='R'; HOST='mymodem'; DOMAIN='modem'; NS='a'; ALG='1'; DLNAD='1'; DUMAOS='0'; SAMBA='1'; MULTIAP='1'; POWER='y'; PRNTR='1'; MMPBX='1'; DECT='1'; UPNP='1';;
-  S)  HOST='s'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0';;
+  A)  HOST='d'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='y';;
+  F)  case "${OPTARG}" in y) ROOT_PROTECT='y';; n) ROOT_PROTECT='n';; u) ROOT_PROTECT='u';; *) ROOT_PROTECT='u'; echo 'ERROR: -F valid options are y, n, or u'; exit 1;; esac;;
+  M)  LITE='y'; ALG='0'; DECT='0'; DLNAD='0'; DUMAOS='0'; MMPBX='0'; MULTIAP='0'; PRNTR='0'; SAMBA='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='y';;
+  R)  LITE='R'; HOST='mymodem'; DOMAIN='modem'; NS='a'; ALG='1'; DLNAD='1'; DUMAOS='0'; SAMBA='1'; MULTIAP='1'; POWER='y'; PRNTR='1'; MMPBX='1'; DECT='1'; UPNP='1'; ROOT_PROTECT='n';;
+  S)  HOST='s'; DOMAIN='gateway'; ALG='0'; DLNAD='0'; SAMBA='0'; PRNTR='0'; UPNP='0'; WPS='0'; ROOT_PROTECT='y';;
   U)  upgrade;;
   ?)  usage;;
  esac
@@ -442,6 +445,33 @@ else
   uci commit dropbear
   SRV_dropbear=$(( $SRV_dropbear + 4 ))
   echo [$SCRIPT]: SSH access correctly configured
+fi
+
+cmp -s /rom/etc/rtfd_persistent_filelist.conf /etc/rtfd_persistent_filelist.conf
+if [ $? -eq 0 ]
+then
+  ROOT_PROTECT_NOW='n'
+else
+  ROOT_PROTECT_NOW='y'
+fi
+if [ "$ROOT_PROTECT" = "u" -o "$ROOT_PROTECT_NOW" = "$ROOT_PROTECT" ]
+then
+  echo [$SCRIPT]: Reset to Factory Defaults root protection unchanged \[$(status2text $ROOT_PROTECT_NOW)\]
+else
+  for f in /etc/passwd /etc/shadow /etc/config/dropbear /etc/dropbear/* /etc/rc.d/*dropbear
+  do
+    if [ "$ROOT_PROTECT" = "y" ]
+    then
+      grep -q -E "^$f$" /etc/rtfd_persistent_filelist.conf
+      if [ $? -eq 1 ]
+      then
+        echo "$f">>/etc/rtfd_persistent_filelist.conf
+      fi
+    else
+      sed -e "/^$(echo $f | sed -e 's|/|\\/|g')\$/d" -i /etc/rtfd_persistent_filelist.conf
+    fi
+  done
+  echo [$SCRIPT]: Reset to Factory Defaults root protection $(status2text $ROOT_PROTECT)
 fi
 
 # End of hardening
