Added -U option to upgrade to latest version

diff --git a/utilities/de-telstra b/utilities/de-telstra
--- a/utilities/de-telstra
+++ b/utilities/de-telstra
@@ -61,7 +61,7 @@ Options:
  -R                    Reset to device defaults
                         (equivalent to: -hmymodem -dmodem -na -ay -cy -fy -py -ry -ty -ey -uy -my -gy -wy -Fn)
  -o                    Configures opkg
- -U                    Check for and download the latest version from GitHub
+ -U                    Download the latest version of $SCRIPT from GitHub
 
 NOTE #1: Default for all optional parameters is u (unchanged)
 NOTE #2: Options marked with * are only applicable if the service is installed
@@ -71,47 +71,25 @@ exit
 }
 
 upgrade() {
-  RESULT=$(curl -s -k -L -I https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT | sed 's/\r//')
-  if [ $? -ne 0 ]
+  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT)
+  if [ "$RESPONSE_CODE" = 200 ]
   then
-      echo "[$SCRIPT] GitHub check of $SCRIPT failed with an unknown error. Do you have an internet connection?"
-      return 5
-  else 
-      STATUS=$(echo $RESULT | grep '^HTTP' | cut -d' ' -f2)
-      LENGTH=$(echo $RESULT | grep '^Content-Length' | cut -d' ' -f2)
-      next=''
-      for t in $(echo $RESULT | tr " " "$IFS")
-      do
-        case "$next" in
-        s) STATUS="$t";next='';;
-        l) LENGTH="$t";next='';;
-        *) case "$t" in
-        "HTTP/1.1") next='s';;
-        "Content-Length:") next='l';;
-        *) next='';;
-        esac
-        esac
-      done
-      case "$STATUS" in
-      200)  if [ -f "$SCRIPT" ]
-            then
-              SIZE=$(ls -l $SCRIPT | tr -s ' ' | cut -d' ' -f5)
-              if [ $SIZE -eq $LENGTH ]
-              then
-              echo "[$SCRIPT] Size of $SCRIPT matches GitHub version - No update required"
-              exit
-              fi
-            fi
-            curl -k -L https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT > $SCRIPT
-            if [ $? -eq 0 ]
-            then
-              chmod +x $SCRIPT
-              echo "[$SCRIPT] Successfully updated $SCRIPT."
-            else
-              echo "[$SCRIPT] Failed to download updated version of $SCRIPT."
-            fi;;
-      *)    echo "[$SCRIPT] GitHub check of $SCRIPT returned $STATUS";;
-      esac
+    curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT
+    if [ $? -eq 0 ]
+    then
+      chmod +x $SCRIPT
+      echo "[$SCRIPT] Successfully downloaded $SCRIPT."
+    else
+      echo "[$SCRIPT] Failed to download $SCRIPT."
+    fi
+  elif [ "$RESPONSE_CODE" = 404 ]
+  then
+    echo "[$SCRIPT] ERROR! Not found on GitHub???"
+  elif [ "$RESPONSE_CODE" = 000 ]
+  then
+    echo "ERROR! No Internet connection???"
+  else
+    echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
   fi
   exit
 }
@@ -887,54 +865,62 @@ then
   cat /proc/cpuinfo | grep -q 'ARMv7 Processor rev 1 (v7l)'
   if [ $? -eq 0 ]
   then
-    if [ $OPKG_DEP -gt 0 -o $(grep -c "^arch " /etc/opkg.conf) -eq 0 -o $(sed -e '/^#/d' /etc/opkg/customfeeds.conf | wc -l) -eq 0 ]
+    if [ $OPKG_DEP -gt 0 -o $(sed -e '/^#/d' -e '/^[ \t]*$/d' /etc/opkg/customfeeds.conf | wc -l) -eq 0 ]
     then
       HOMEWARE=$(uci get version.@version[0].version | cut -d. -f1)
-      if [ "$HOMEWARE" -eq 17 -o "$HOMEWARE" -eq 18 ]
+      if [ "$HOMEWARE" -eq 17 -o "$HOMEWARE" -eq 18 -o "$HOMEWARE" -eq 20 ]
       then
-        if [ "$HOMEWARE" -eq 18 -a $OPKG_DEP -gt 0 ]
+        if [ $OPKG_DEP -gt 0 ]
         then
+          sed -e '/macoers/d' -i /etc/opkg/customfeeds.conf
           echo [$SCRIPT]: Re-configuring opkg for Homeware $HOMEWARE \(repository moved\)...
         else
           echo [$SCRIPT]: Configuring opkg for Homeware $HOMEWARE...
         fi
-        echo "arch all 1">>/etc/opkg.conf
-        echo "arch noarch 1">>/etc/opkg.conf
-        case "$HOMEWARE" in
-          17) cat <<-HW17 | sed -e 's/^[ \t]*//g' > /etc/opkg/customfeeds.conf
-                src/gz base https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/base
-                src/gz luci https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/luci
-                src/gz management https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/management
-                src/gz packages https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/packages
-                src/gz routing https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/routing
-                src/gz telephony https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/telephony
-HW17
-;;
-          18) echo "arch arm_cortex-a9 10">>/etc/opkg.conf
-              echo "arch arm_cortex-a9_neon 20">>/etc/opkg.conf
-              cat <<-HW18 | sed -e 's/^[ \t]*//g' > /etc/opkg/customfeeds.conf
-                src/gz chaos_calmer_base_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/base
-                src/gz chaos_calmer_packages_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/packages
-                src/gz chaos_calmer_luci_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/luci
-                src/gz chaos_calmer_routing_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/routing
-                src/gz chaos_calmer_telephony_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/telephony
-                src/gz chaos_calmer_core_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/target/packages
-HW18
-;;
-        esac
-        echo "arch brcm63xx-tch 30">>/etc/opkg.conf
-        sed -e 's/^src/#src/' -i /etc/opkg/distfeeds.conf
         ping -c 1 -W 2 -q 1.1.1.1 >/dev/null 2>&1
         if [ $? -eq 0 ]
         then
-          opkg update
-          echo [$SCRIPT]: Updating System CA certificates
-          opkg install --force-overwrite ca-certificates
+          echo "dest root">/etc/opkg.conf
+          echo "dest ram /tmp">>/etc/opkg.conf
+          echo "lists_dir ext /var/opkg-lists">>/etc/opkg.conf
+          echo "option overlay_root /overlay">>/etc/opkg.conf
+          echo "arch all 1">>/etc/opkg.conf
+          echo "arch noarch 1">>/etc/opkg.conf
+          echo "arch arm_cortex-a9 10">>/etc/opkg.conf
+          echo "arch arm_cortex-a9_neon 20">>/etc/opkg.conf
+          echo "arch brcm63xx-tch 30">>/etc/opkg.conf
+          case "$HOMEWARE" in
+            17) cat <<-HW17 | sed -e 's/^[ \t]*//g' > /etc/opkg/customfeeds.conf
+              src/gz base https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/base
+              src/gz luci https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/luci
+              src/gz management https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/management
+              src/gz packages https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/packages
+              src/gz routing https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/routing
+              src/gz telephony https://raw.githubusercontent.com/BoLaMN/brcm63xx-tch/master/packages/telephony
+HW17
+;;
+          18|20) cat <<-HW18 | sed -e 's/^[ \t]*//g' > /etc/opkg/customfeeds.conf
+              src/gz chaos_calmer_base_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/base
+              src/gz chaos_calmer_packages_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/packages
+              src/gz chaos_calmer_luci_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/luci
+              src/gz chaos_calmer_routing_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/routing
+              src/gz chaos_calmer_telephony_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/telephony
+              src/gz chaos_calmer_core_macoers https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/target/packages
+HW18
+;;
+          esac
+          sed -e 's/^src/#src/' -i /etc/opkg/distfeeds.conf
+          echo [$SCRIPT]: Downloading and installing packages required for repository access...
+          SRC='https://downloads.openwrt.org/releases/packages-21.02/arm_cortex-a9/base/'
+          IPK=$(curl -sk $SRC/Packages.gz | gunzip | grep '^Filename: ca-certificates' | cut -d' ' -f2)
+          curl -sk $SRC/$IPK -o /tmp/$IPK && opkg --force-overwrite install /tmp/$IPK 2>&1 | logger -s -t rpc.gui.opkg -p user.info && rm /tmp/$IPK
+          echo [$SCRIPT]: Updating local package list
+          opkg update | logger -s -t rpc.gui.opkg -p user.info;
         else
-          echo [$SCRIPT]: WARNING: Unable to execute opkg update - You do not have an internet connection???
+          echo [$SCRIPT]: WARNING: No internet connection??? opkg not configured...
         fi
       else
-        echo [$SCRIPT]: Sorry!! I do not know how to configure opkg for Firmware Version $(uci get version.@version[0].version)
+        echo [$SCRIPT]: Sorry!! I do not know how to configure opkg for Firmware Version $(uci get version.@version[0].marketing_version)
       fi
     else
       echo [$SCRIPT]: Looks like opkg has already been configured...
diff --git a/utilities/intercept-dns b/utilities/intercept-dns
--- a/utilities/intercept-dns
+++ b/utilities/intercept-dns
@@ -25,9 +25,34 @@ Options:
                 be re-specified with -x. 
  -6           Do NOT apply blocking to IPv6 DNS requests.
  -r           Remove DNS interception.
+ -U           Download the latest version of $SCRIPT from GitHub
 
 EOH
 exit
+}
+
+upgrade() {
+  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT)
+  if [ "$RESPONSE_CODE" = 200 ]
+  then
+    curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT
+    if [ $? -eq 0 ]
+    then
+      chmod +x $SCRIPT
+      echo "[$SCRIPT] Successfully downloaded $SCRIPT."
+    else
+      echo "[$SCRIPT] Failed to download $SCRIPT."
+    fi
+  elif [ "$RESPONSE_CODE" = 404 ]
+  then
+    echo "[$SCRIPT] ERROR! Not found on GitHub???"
+  elif [ "$RESPONSE_CODE" = 000 ]
+  then
+    echo "ERROR! No Internet connection???"
+  else
+    echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
+  fi
+  exit
 }
 
 # Options
@@ -41,7 +66,7 @@ GREEN='\033[1;32m'
 RED='\033[0;31m'
 NC='\033[0m' # No Color
 
-while getopts :d:x:r6 option
+while getopts :d:x:r6U option
 do
   case "${option}" in
     d)  echo "$OPTARG" | grep -q -E "$IPv4_PATTERN"
@@ -61,6 +86,7 @@ do
         fi;;
     r)  REMOVE="y";;
     6)  IPv6="n";;
+    U)  upgrade;;
     ?)  usage;;
   esac
 done
diff --git a/utilities/mtd-backup b/utilities/mtd-backup
--- a/utilities/mtd-backup
+++ b/utilities/mtd-backup
@@ -19,9 +19,34 @@ Options:
  -y  Bypass confirmation prompt (answers 'y')
  -C  Adds or removes the scheduled daily backup cron job
  -P  Reports the USB backup path
+ -U  Download the latest version of $SCRIPT from GitHub
 
 EOH
 exit
+}
+
+upgrade() {
+  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT)
+  if [ "$RESPONSE_CODE" = 200 ]
+  then
+    curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT
+    if [ $? -eq 0 ]
+    then
+      chmod +x $SCRIPT
+      echo "[$SCRIPT] Successfully downloaded $SCRIPT."
+    else
+      echo "[$SCRIPT] Failed to download $SCRIPT."
+    fi
+  elif [ "$RESPONSE_CODE" = 404 ]
+  then
+    echo "[$SCRIPT] ERROR! Not found on GitHub???"
+  elif [ "$RESPONSE_CODE" = 000 ]
+  then
+    echo "ERROR! No Internet connection???"
+  else
+    echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
+  fi
+  exit
 }
 
 CRON=N
@@ -38,7 +63,7 @@ then
   exit 1
 fi
 
-while getopts :celovyCP option
+while getopts :celovyCPU option
 do
  case "${option}" in
   C)  CRON=Y;;
@@ -49,6 +74,7 @@ do
   o)  DUMP_OVL=Y;;
   v)  DEBUG=Y;;
   y)  YES=Y;;
+  U)  upgrade;;
   *)  usage;;
  esac
 done
@@ -91,7 +117,7 @@ then
     mm=$(awk 'BEGIN{srand();print int(rand()*59);}')
     hh=$(awk 'BEGIN{srand();print int(rand()*3)+2;}')
     echo "$mm $hh * * * $(cd $(dirname $0); pwd)/$SCRIPT -c -e -o -y" >> /etc/crontabs/root
-    echo Backup has been scheduled to execute at $hh:${mm}am every day.
+    echo Backup has been scheduled to execute at $hh:$(printf '%02d' $mm)am every day.
     echo Execution messages will be written to the system log, and can be viewed with the following command:
     echo
     echo "  logread -e mtd-backup"
diff --git a/utilities/mtd-restore b/utilities/mtd-restore
--- a/utilities/mtd-restore
+++ b/utilities/mtd-restore
@@ -3,21 +3,55 @@
 SCRIPT="$(basename $0)"
 VARIANT=$(uci -q get env.var.variant_friendly_name)
 
-if [ "o$1" = "o-?" ]; then
+usage() {
 cat <<EOH
 Restores the MTD partitions from an attached USB device. Only changed partitions are restored.
 
-Usage: $0 [partition]
+Usage: $0 [-U] [partition]
 
 Parameters:
  partition  the partition to restored. (Optional)
               Specify either the device (e.g. "mtd2") or name (e.g. "rootfs_data")
+ -U         Download the latest version of $SCRIPT from GitHub
 
 If no partition is specified for restore, ALL partitions that have been altered will be restored.
 
 EOH
 exit
-fi
+}
+
+upgrade() {
+  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT)
+  if [ "$RESPONSE_CODE" = 200 ]
+  then
+    curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT
+    if [ $? -eq 0 ]
+    then
+      chmod +x $SCRIPT
+      echo "[$SCRIPT] Successfully downloaded $SCRIPT."
+    else
+      echo "[$SCRIPT] Failed to download $SCRIPT."
+    fi
+  elif [ "$RESPONSE_CODE" = 404 ]
+  then
+    echo "[$SCRIPT] ERROR! Not found on GitHub???"
+  elif [ "$RESPONSE_CODE" = 000 ]
+  then
+    echo "ERROR! No Internet connection???"
+  else
+    echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
+  fi
+  exit
+}
+
+while getopts :U option
+do
+ case "${option}" in
+  U)  upgrade;;
+  *)  usage;;
+ esac
+done
+shift $((OPTIND-1))
 
 USB="$(ls /mnt/usb | head -n1)"
 if [ -z "$USB" ]
diff --git a/utilities/reset-to-factory-defaults-with-root b/utilities/reset-to-factory-defaults-with-root
--- a/utilities/reset-to-factory-defaults-with-root
+++ b/utilities/reset-to-factory-defaults-with-root
@@ -16,9 +16,34 @@ Options:
  -I n.n.n.n   Use IP address n.n.n.n after reset and reboot.
  -i           Keep existing IP address [$(ip address show dev br-lan | grep "inet " | tr -s " " | cut -d" " -f3 | cut -d/ -f1)] after reset and reboot.
  -n           Do NOT reboot.
+ -U           Download the latest version of $SCRIPT from GitHub
 
 EOH
 exit
+}
+
+upgrade() {
+  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT)
+  if [ "$RESPONSE_CODE" = 200 ]
+  then
+    curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT
+    if [ $? -eq 0 ]
+    then
+      chmod +x $SCRIPT
+      echo "[$SCRIPT] Successfully downloaded $SCRIPT."
+    else
+      echo "[$SCRIPT] Failed to download $SCRIPT."
+    fi
+  elif [ "$RESPONSE_CODE" = 404 ]
+  then
+    echo "[$SCRIPT] ERROR! Not found on GitHub???"
+  elif [ "$RESPONSE_CODE" = 000 ]
+  then
+    echo "ERROR! No Internet connection???"
+  else
+    echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
+  fi
+  exit
 }
 
 ACTIVE="$(cat /proc/banktable/active)"
@@ -28,7 +53,7 @@ FIRMWARE=""
 REBOOT="Y"
 IPADDR=""
 CWMP=""
-while getopts :bf:I:inc option
+while getopts :bf:I:incU option
 do
  case "${option}" in
   b)  BKUP="Y";;
@@ -44,6 +69,7 @@ do
   i)  IPADDR="$(ip address show dev br-lan | grep "inet " | tr -s " " | cut -d" " -f3 | cut -d/ -f1)";;
   n)  REBOOT="N";;
   c)  CWMP="uci delete cwmpd.cwmpd_config.acs_url;uci set cwmpd.cwmpd_config.state='0';uci commit cwmpd;/etc/init.d/cwmpd stop;";;
+  U)  upgrade;;
   *)  usage;;
  esac
 done
