Removed -f & rootfs_data is default backup source

diff --git a/utilities/mtd-restore b/utilities/mtd-restore
--- a/utilities/mtd-restore
+++ b/utilities/mtd-restore
@@ -3,11 +3,10 @@
 SCRIPT="$(basename $0)"
 VARIANT=$(uci -q get env.var.variant_friendly_name)
 VERSION=$(uci -q get version.@version[0].marketing_version)
-BOOTED=$(cat /proc/banktable/booted)
 
 usage() {
 cat <<EOH
-Restores MTD partitions from an attached USB device or SSHFS filesystem. Only
+Restores partitions from an attached USB device or SSHFS filesystem. Only
 changed partitions are restored (unless -s is specified).
 
 USB devices have priority over SSHFS filesystems.
@@ -18,22 +17,20 @@ Options:
  -d directory   The name of the directory on the USB device or SSHFS
                   filesystem containing the backups. If not specified,
                   defaults to: backups or backups-$VERSION
- -f             Restore rootfs_data and $BOOTED
  -r             Reboot after last partition successfully restored
  -s             Skip check for changed partitions and always restore
  -v             Skip verification of image checksum (if it exists i.e. if
                   mtd-backup was NOT executed with the -s option)
- -q             Quiet mode (i.e. no [w] on writing partition)
+ -q             Quiet mode
  -U             Download the latest version of $SCRIPT from GitHub
-                  Do NOT specify any other parameters or options if doing a
-                  version upgrade.
+                  Do NOT specify any other parameters or options if doing
+                  a version upgrade.
 Parameters:
  partition      One or more partitions to restored.
                   Specify either the device (e.g. mtd2) or name
                     (e.g. rootfs_data or data)
                   Do not specify the device variant prefix (e.g. $VARIANT-)
-                  If not specified and -f not specified, defaults to:
-                    mtd2-rootfs_data
+                  If not specified, defaults to: rootfs_data
 
 EOH
 exit
@@ -41,21 +38,17 @@ exit
 
 upgrade() {
   RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT)
-  if [ "$RESPONSE_CODE" = 200 ]
-  then
+  if [ "$RESPONSE_CODE" = 200 ]; then
     curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT
-    if [ $? -eq 0 ]
-    then
+    if [ $? -eq 0 ]; then
       chmod +x $SCRIPT
       echo "[$SCRIPT] Successfully downloaded $SCRIPT."
     else
       echo "[$SCRIPT] Failed to download $SCRIPT."
     fi
-  elif [ "$RESPONSE_CODE" = 404 ]
-  then
+  elif [ "$RESPONSE_CODE" = 404 ]; then
     echo "[$SCRIPT] ERROR! Not found on GitHub???"
-  elif [ "$RESPONSE_CODE" = 000 ]
-  then
+  elif [ "$RESPONSE_CODE" = 000 ]; then
     echo "ERROR! No Internet connection???"
   else
     echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
@@ -64,7 +57,6 @@ upgrade() {
 }
 
 DIR="backups"
-DFLT_RESTORE=""
 QUIET=""
 REBOOT=N
 SKIP_CHG_CHECK=N
@@ -75,11 +67,9 @@ ORANGE='\033[0;33m'
 RED='\033[0;31m'
 NC='\033[0m' # No Color
 
-while getopts :d:fqrsvU option
-do
+while getopts :d:qrsvU option; do
  case "${option}" in
   d)  DIR="$(echo $OPTARG | sed -e 's,/$,,')";;
-  f)  DFLT_RESTORE="rootfs_data $BOOTED";;
   q)  QUIET="-q";;
   r)  REBOOT=Y;;
   s)  SKIP_CHG_CHECK=Y;;
@@ -92,11 +82,9 @@ shift $((OPTIND-1))
 
 MOUNT_PATH=$(uci get mountd.mountd.path)
 USB="$(ls $MOUNT_PATH | head -n1)"
-if [ -z "$USB" ]
-then
+if [ -z "$USB" ]; then
   SSHFS=$(grep -m 1 fuse\.sshfs /proc/mounts | cut -d" " -f2)
-  if [ -z "$SSHFS" ]
-  then
+  if [ -z "$SSHFS" ]; then
     echo -e "$(date +%F@%X): ${RED}ERROR! No USB device or mounted SSHFS filesystem found${NC}"
     exit 2
   else
@@ -106,10 +94,8 @@ else
   SOURCE=${MOUNT_PATH}${USB}/${DIR}
 fi
 
-if [ ! -d $SOURCE ]
-then
-  if [ -d $SOURCE-$VERSION ]
-  then
+if [ ! -d $SOURCE ]; then
+  if [ -d $SOURCE-$VERSION ]; then
     SOURCE=$SOURCE-$VERSION
   else
     echo -e "$(date +%F@%X): ${RED}ERROR! Backup source $SOURCE not found${NC}"
@@ -117,18 +103,12 @@ then
   fi
 fi
 
-if [ $# -eq 0 -a -z "$DFLT_RESTORE" ]
-then
-  DFLT_RESTORE="mtd2-rootfs_data"
-fi
-for p in $DFLT_RESTORE $*
-do
+[ $# -eq 0 ] && DFLT_RESTORE="rootfs_data"
+for p in $DFLT_RESTORE $*; do
   COUNT=$(ls $SOURCE 2>/dev/null | grep -E "$VARIANT-.*$p.*\.img\.gz" | wc -l)
-  if [ $COUNT -eq 1 ]
-  then
+  if [ $COUNT -eq 1 ]; then
     IMAGES="$IMAGES $(ls $SOURCE 2>/dev/null | grep -E "$VARIANT-.*$p.*\.img\.gz")"
-  elif [ $COUNT -eq 0 ]
-  then
+  elif [ $COUNT -eq 0 ]; then
     echo -e "$(date +%F@%X): ${ORANGE}WARNING! Could not find a backup matching $p - IGNORED${NC}"
   else
     echo -e "$(date +%F@%X): ${ORANGE}WARNING! Found $COUNT backups matching $p - IGNORED${NC}"
@@ -136,8 +116,7 @@ do
   fi
 done
 
-if [ -z "$IMAGES" ]
-then
+if [ -z "$IMAGES" ]; then
   echo -e "$(date +%F@%X): ${RED}ERROR! No valid backups selected for restore${NC}"
   exit 2
 fi
@@ -145,8 +124,7 @@ fi
 IMAGES=$(echo $IMAGES | tr " " "\n" | sort -u | xargs)
 LAST=""
 echo "$(date +%F@%X): $(echo $IMAGES | wc -w) backups selected for restore:"
-for gz in $IMAGES
-do
+for gz in $IMAGES; do
   echo "                     -> $gz"
   LAST="$gz"
 done
@@ -165,51 +143,46 @@ fi
 echo "$(date +%F@%X): Cleaning up any old images..."
 find $SOURCE -name "$VARIANT-*.img" -exec rm {} \;
 
-for gz in $IMAGES
-do
+RESTORED="$(mktemp)"
+
+for gz in $IMAGES; do
   echo "$(date +%F@%X): PROCESSING backup $gz"
 
-  echo $gz | grep -q -e '-mtd0-'
-  if [ $? -eq 0 ]; then
+  if echo $gz | grep -qe '-mtd0-'; then
     echo -e "$(date +%F@%X): ${ORANGE}SORRY! You cannot restore mtd0 usng this script${NC}"
     continue
   fi
 
-  basename $gz | sed -e "s/^$VARIANT-\(mtd.\)-\(.*\).img.gz$/\1 \2/" | while read -r dev name
-  do
+  basename $gz | sed -e "s/^$VARIANT-\(mtd\)\([^-]*\)-\(.*\).img.gz$/\1\2 \3/" | while read -r dev name; do
+    TARGET="/dev/${dev}"
+    PARTITION="$(echo $name | cut -d- -f1)"
     SHA256CHK=N
-    if [ $SKIP_CHG_CHECK = N ]
-    then
-      if [ -f $SOURCE/$VARIANT-$dev-$name.img.sha256= ]
-      then
+
+    if [ $SKIP_CHG_CHECK = N ]; then
+      if [ -f $SOURCE/$VARIANT-$dev-$name.img.sha256= ]; then
         SHA256CHK=Y
         SHA256OLD="$(cat $SOURCE/$VARIANT-$dev-$name.img.sha256= | cut -d' ' -f1)"
-      elif [ -f $SOURCE/$VARIANT-$dev-$name.img.sha256 ]
-      then
+      elif [ -f $SOURCE/$VARIANT-$dev-$name.img.sha256 ]; then
         SHA256OLD="$(cat $SOURCE/$VARIANT-$dev-$name.img.sha256 | cut -d' ' -f1)"
       else
         echo -e "$(date +%F@%X): ${ORANGE}SKIPPED restore of $gz: $VARIANT-$dev-$name.img.sha256 does not exist?${NC}"
         continue
       fi
-      echo "$(date +%F@%X): CALCULATING current SHA256 checksum for $dev"
-      SHA256=$(sha256sum "/dev/${dev}ro" | cut -d' ' -f1)
+      echo "$(date +%F@%X): CALCULATING current SHA256 checksum for $dev ($PARTITION)"
+      [ -e "${TARGET}ro" ] && source="${TARGET}ro" || source="$TARGET"
+      SHA256=$(sha256sum "$source" | cut -d' ' -f1)
     else
       SHA256OLD="SHA256OLD"
       SHA256="SHA256"
     fi
 
-    target="$(echo $name | cut -d- -f1)"
-
-    if [ "$SHA256" = "$SHA256OLD" ]
-    then
+    if [ "$SHA256" = "$SHA256OLD" ]; then
       echo -e "$(date +%F@%X): ${GREEN}SKIPPED restore of $gz - Checksums for $dev match therefore image unchanged${NC}"
     else
       echo "$(date +%F@%X): EXPANDING $dev backup to temporary file $SOURCE/$VARIANT-$dev-$name.img"
-      if [ $SKIP_SHA_CHECK = N -a $SHA256CHK = Y ]
-      then
+      if [ $SKIP_SHA_CHECK = N -a $SHA256CHK = Y ]; then
         SHA256IMG="$(gzip -dc $SOURCE/$gz | tee $SOURCE/$VARIANT-$dev-$name.img | sha256sum | cut -d' ' -f1)"
-        if [ "$SHA256OLD" = "$SHA256IMG" ]
-        then
+        if [ "$SHA256OLD" = "$SHA256IMG" ]; then
           echo "$(date +%F@%X): VERIFICATION of $SOURCE/$VARIANT-$dev-$name.img checksum SUCCEEDED"
           VERIFIED=0
         else
@@ -222,21 +195,21 @@ do
         gzip -dc $SOURCE/$gz > $SOURCE/$VARIANT-$dev-$name.img
         VERIFIED=$?
       fi
-      if [ $VERIFIED -eq 0 ]
-      then
-        if [ $REBOOT = Y -a "$LAST" = "$gz" ]
-        then
-          echo "$(date +%F@%X): RESTORING $SOURCE/$VARIANT-$dev-$name.img to partion $dev ($target) and rebooting"
-          mtd $QUIET -r -e $target write $SOURCE/$VARIANT-$dev-$name.img $target
+      if [ $VERIFIED -eq 0 ]; then
+        # http://www.infradead.org/pipermail/linux-mtd/2017-August/076260.html
+        # If you want to backup/restore UBIFS, dd from /dev/ubiX_Y and restore using ubiupdatevol.
+        if [ $REBOOT = Y -a "$LAST" = "$gz" ]; then
+          echo "$(date +%F@%X): RESTORING $SOURCE/$VARIANT-$dev-$name.img to partion $dev ($PARTITION) and rebooting"
+          mtd $QUIET -r -e $PARTITION write $SOURCE/$VARIANT-$dev-$name.img $PARTITION
         else
-          echo "$(date +%F@%X): RESTORING $SOURCE/$VARIANT-$dev-$name.img to partion $dev ($target)"
-          mtd $QUIET -e $target write $SOURCE/$VARIANT-$dev-$name.img $target
+          echo "$(date +%F@%X): RESTORING $SOURCE/$VARIANT-$dev-$name.img to partion $dev ($PARTITION)"
+          mtd $QUIET -e $PARTITION write $SOURCE/$VARIANT-$dev-$name.img $PARTITION
         fi
-        if [ $? -eq 0 ]
-        then
-          echo -e "$(date +%F@%X): ${GREEN}RESTORED $SOURCE/$VARIANT-$dev-$name.img to partion $dev ($target)${NC}"
+        if [ $? -eq 0 ]; then
+          echo -e "$(date +%F@%X): ${GREEN}RESTORED $SOURCE/$VARIANT-$dev-$name.img to partion $dev ($PARTITION)${NC}"
+          echo $SOURCE/$VARIANT-$dev-$name.img > $RESTORED
         else
-          echo -e "$(date +%F@%X): ${RED}FAILED to restore $SOURCE/$VARIANT-$dev-$name.img to partion $dev ($target)!${NC}"
+          echo -e "$(date +%F@%X): ${RED}FAILED to restore $SOURCE/$VARIANT-$dev-$name.img to partion $dev ($PARTITION)!${NC}"
         fi
       else
         echo -e "$(date +%F@%X): ${RED}FAILED to successfully expand $dev backup to $SOURCE/$VARIANT-$dev-$name.img!${NC}"
@@ -246,4 +219,6 @@ do
   done
 done
 
-echo "$(date +%F@%X): COMPLETED - You may need to manually power cycle the device now..."
+echo "$(date +%F@%X): COMPLETED"
+[ $(cat $RESTORED | wc -l) -gt 0 ] && echo -e "$(date +%F@%X): ${ORANGE}You may need to manually power cycle the device now...${NC}"
+rm -rf $RESTORED
