Kill writing processes before restore

diff --git a/utilities/overlay-restore b/utilities/overlay-restore
--- a/utilities/overlay-restore
+++ b/utilities/overlay-restore
@@ -2,6 +2,12 @@
 
 SCRIPT="$(basename $0)"
 
+GREEN='\033[1;32m'
+GREY='\033[90m'
+ORANGE='\033[0;33m'
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+
 SERIAL=$(uci get env.var.serial)
 VERSION=$(uci get version.@version[0].version | cut -d- -f1)
 VARIANT=$(uci -q get env.var.variant_friendly_name | sed -e 's/TLS//')
@@ -15,6 +21,7 @@ else
   NOT_BOOTED="bank_$(bootmgr partition notbooted)"
 fi
 
+#region usage
 usage() {
 cat <<EOH
 Restores an overlay tar backup. By default, both bank_1 and bank_2 
@@ -46,36 +53,33 @@ Parameters:
 EOH
 exit
 }
+#endregion
 
+#region upgrade
 upgrade() {
   RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT)
   if [ "$RESPONSE_CODE" = 200 ]; then
     curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT
     if [ $? -eq 0 ]; then
       chmod +x $SCRIPT
-      echo "[$SCRIPT] Successfully downloaded $SCRIPT."
+      echo -e "${GREEN}SUCCESS:  Downloaded $SCRIPT.${NC}"
     else
-      echo "[$SCRIPT] Failed to download $SCRIPT."
+      echo -e "${RED}ERROR:    Failed to download $SCRIPT?${NC}"
     fi
   elif [ "$RESPONSE_CODE" = 404 ]; then
-    echo "[$SCRIPT] ERROR! Not found on GitHub???"
+    echo -e "${RED}ERROR:    Not found on GitHub???${NC}"
   elif [ "$RESPONSE_CODE" = 000 ]; then
-    echo "ERROR! No Internet connection???"
+    echo -e "${RED}ERROR:    No Internet connection???${NC}"
   else
-    echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
+    echo -e "${RED}ERROR:    Unknown response code $RESPONSE_CODE${NC}"
   fi
   exit
 }
+#endregion
 
 REBOOT="Y"
 RESTORE="./bank_1 ./bank_2"
 VERBOSE=""
-
-GREEN='\033[1;32m'
-GREY='\033[90m'
-ORANGE='\033[0;33m'
-RED='\033[0;31m'
-NC='\033[0m' # No Color
 
 while getopts :12bnpvU option; do
  case "${option}" in
@@ -91,25 +95,27 @@ while getopts :12bnpvU option; do
 done
 [ "$REBOOT" = "Y" -a "$RESTORE" = "./$NOT_BOOTED" ] && REBOOT="N"
 
+#region filename
 shift $((OPTIND-1))
 FILENAME="$1"
 if [ -z "$FILENAME" ]; then
   MOUNT_PATH=$(uci get mountd.mountd.path)
   USB="$(ls $MOUNT_PATH | head -n1)"
   if [ -z "$USB" ]; then
-    echo -e "$(date +%F@%X): ${RED}ERROR! No USB device found${NC}"
+    echo -e "${RED}ERROR:    No USB device found${NC}"
     exit 2
   else
     FILENAME=${MOUNT_PATH}${USB}/backups/$VARIANT-$SERIAL-$VERSION-overlay-files-backup.tgz
   fi
 fi
-
 if [ ! -e $FILENAME ]; then
-  echo -e "$(date +%F@%X): ${RED}ERROR! $FILENAME not found${NC}"
+  echo -e "${RED}ERROR:    $FILENAME not found${NC}"
   exit 2
 fi
+#endregion
 
-echo -e "$(date +%F@%X): PRESERVING MAC address configuration..."
+#region preserve MAC addresses
+echo -e "${GREEN}ACTION:   PRESERVING MAC address configuration..."
 MAC_TMP=$(mktemp)
 MAC_UCI=$(mktemp)
 echo '#!/bin/sh
@@ -122,85 +128,96 @@ uci show | grep -v '^env\.' | grep -Ff $MAC_TMP | sed -e 's/^/uci set /' >> $MAC
 echo 'uci commit' >> $MAC_UCI
 rm -f $MAC_TMP
 chmod +x $MAC_UCI
+#endregion
 
-echo -e "$(date +%F@%X): CHECKING ${GREEN}${FILENAME}${NC}..."
-echo -e "$(date +%F@%X):  ==> NOTE: Backup was taken ${GREEN}$(date -r $FILENAME)${NC}"
-[ "$(hexdump -e '/2 "%02x"' -n 2 $FILENAME)" = "8b1f" ] && { GZIP="z"; echo "$(date +%F@%X):  ==> NOTE: Backup is compressed"; } || { GZIP=""; echo "$(date +%F@%X):  ==> NOTE: Backup is NOT compressed"; }
+echo -e "${GREEN}ACTION:   CHECKING ${GREEN}${FILENAME}${NC}..."
+echo -e "INFO:     ==> Backup was taken ${GREEN}$(date -r $FILENAME)${NC}"
+[ "$(hexdump -e '/2 "%02x"' -n 2 $FILENAME)" = "8b1f" ] && { GZIP="z"; echo "INFO:     ==> Backup is compressed"; } || { GZIP=""; echo "INFO:     ==> Backup is NOT compressed"; }
 if basename $FILENAME | grep -qE '^[^-]+-[^-]+-[0-9a-z.]+-overlay-files-backup.tgz$'; then
   set -- $(basename $FILENAME | tr '-' ' ')
-  [ "$VARIANT" = "$1" ] && echo -e "$(date +%F@%X):  ==> NOTE: Backup was taken on same device variant (${GREEN}$1${NC})" || echo -e "$(date +%F@%X):  ==> ${ORANGE}WARNING:${NC} Backup was taken on different device (${ORANGE}$1 ${NC}!=${ORANGE} $VARIANT${NC})"
-  [ "$SERIAL" = "$2" ] && echo -e "$(date +%F@%X):  ==> NOTE: Backup was taken on this device (Serial Number ${GREEN}$2${NC})" || echo -e "$(date +%F@%X):  ==> ${ORANGE}WARNING:${NC} Backup was taken on different device (${ORANGE}$2 ${NC}!=${ORANGE} $SERIAL${NC})"
-  [ "$VERSION" = "$3" ] && echo -e "$(date +%F@%X):  ==> NOTE: Backup was taken on same booted firmware (${GREEN}$3${NC})" || echo -e "$(date +%F@%X):  ==> ${ORANGE}WARNING:${NC} Backup was taken on different booted firmware (${ORANGE}$3 ${NC}!=${ORANGE} $VERSION${NC})"
+  [ "$VARIANT" = "$1" ] && echo -e "INFO:     ==> Backup was taken on same device variant (${GREEN}$1${NC})" || echo -e "${ORANGE}WARNING:${NC}  ==> Backup was taken on different device (${ORANGE}$1 ${NC}!=${ORANGE} $VARIANT${NC})"
+  [ "$SERIAL" = "$2" ] && echo -e "INFO:     ==> Backup was taken on this device (Serial Number ${GREEN}$2${NC})" || echo -e "${ORANGE}WARNING:${NC}  ==> Backup was taken on different device (${ORANGE}$2 ${NC}!=${ORANGE} $SERIAL${NC})"
+  [ "$VERSION" = "$3" ] && echo -e "INFO:     ==> Backup was taken on same booted firmware (${GREEN}$3${NC})" || echo -e "${ORANGE}WARNING:${NC}  ==> Backup was taken on different booted firmware (${ORANGE}$3 ${NC}!=${ORANGE} $VERSION${NC})"
 fi
 for DIR in $RESTORE; do
   COUNT=$(tar -t${GZIP} -f $FILENAME $DIR 2>/dev/null | wc -l)
   if [ $? -ne 0 -o $COUNT -eq 0 ]; then
-    echo -e "$(date +%F@%X):  ==> ${RED}ERROR: No files found in backup for ${DIR}!${NC} Removing directory from restore..."
+    echo -e "${ORANGE}WARNING:${NC}  ==> No files found in backup for ${DIR}! Removing directory from restore..."
     RESTORE=$(echo $RESTORE | sed -e "s|$DIR||" | xargs)
   elif [ $COUNT -eq 1 ]; then
-    echo -e "$(date +%F@%X):  ==> NOTE: ${GREEN}One${NC} file will be restored into ${GREEN}$DIR${NC}"
+    echo -e "INFO:     ==> ${GREEN}One${NC} file will be restored into ${GREEN}$DIR${NC}"
   elif [ $COUNT -gt 1 ]; then
-    echo -e "$(date +%F@%X):  ==> NOTE: ${GREEN}${COUNT}${NC} files will be restored into ${GREEN}$DIR${NC}"
+    echo -e "INFO:     ==> ${GREEN}${COUNT}${NC} files will be restored into ${GREEN}$DIR${NC}"
   fi
 done
 
-[ -z "$RESTORE" ] && { echo -e "$(date +%F@%X): ${RED}ERROR! Nothing to restore?${NC}"; exit 1; }
+[ -z "$RESTORE" ] && { echo -e "${RED}ERROR:    Nothing to restore?${NC}"; exit 1; }
 
-echo -e "$(date +%F@%X): NOTE: Restoring ${GREEN}${RESTORE}${NC} into /overlay"
-echo -e "$(date +%F@%X): NOTE: Booted bank is ${GREEN}${BOOTED}${NC}"
-[ $REBOOT = Y ] && echo -e "$(date +%F@%X): ${ORANGE}NOTE: Device will be rebooted after restoring!${NC}" || echo -e "$(date +%F@%X): NOTE: Device will ${ORANGE}NOT${NC} be rebooted after restoring"
-echo -e -n "$(date +%F@%X): ${GREEN}If you wish to commence the restore, enter y otherwise just press [Enter] to exit:${NC} "
+echo -e "INFO:     Restoring ${GREEN}${RESTORE}${NC} into /overlay"
+echo -e "INFO:     Booted bank is ${GREEN}${BOOTED}${NC}"
+[ $REBOOT = Y ] && echo -e "${ORANGE}WARNING:${NC}  Device will be rebooted after restoring!${NC}" || echo -e "INFO:     Device will ${ORANGE}NOT${NC} be rebooted after restoring"
+echo -en "ACTION:   ${GREEN}If you wish to commence the restore, enter y otherwise just press [Enter] to exit:${NC} "
 read
 [ "$REPLY" != "y" -a "$REPLY" != "Y" ] && exit
 
-services="watchdog-tch \
-          adblock AdGuardHome autoreset \
-          bqos bulkdata \
-          cron cupsd cwmpd cwmpdboot \
-          ddns dlnad dosprotect dumaos dumaos_qos_tweaks \
-          hotspotd \
-          intercept iperf ipset iqos \
-          led ledfw lotagent lte-doctor-logger lxc lxc.mount \
-          minidlna miniupnpd-tch mmpbxbrcmdect mmpbxd mmpbxd_lite mmpbxfwctl mosquitto mqttjson-services mud multiap_agent multiap_controller multiap_vendorextensions mwan \
-          ndhttpd ndproxy nfcd nginx nqe \
-          pinholehelper \
-          qos qos_tch \
-          ra redirecthelper rsyncd \
-          samba samba-nmbd socat static-wan-routes-monitor supervision sync-adguard-home-data sysntpd \
-          telemetry-daemon tls-thor tod trafficmon transformer tproxy \
-          uhttpd \
-          wansensing wfa-testsuite-daemon wifi-doctor-agent wol \
-          xl2tpd"
-sp='/-\|'
-i=1
-c=0
-for service in $services; do
-  if [ -x /etc/init.d/$service ]; then
-    if /etc/init.d/$service enabled; then
-      echo -en "\r$(date +%F@%X): STOPPING service: $(echo $sp | cut -c $i) ${GREY}$service${NC}"
-      c=$(( $c - ${#service} ))
-      while [ $c -gt 0 ]; do echo -n " "; c=$(( $c - 1 )); done
-      c=${#service}
-      [ $i -lt 4 ] && i=$(( $i + 1 )) || i=1
-      /etc/init.d/$service stop >/dev/null 2>&1
+sp='/-\|'; i=1
+
+for pid in $(pgrep flock); do
+  fd=$(sed -e 's/^.*flock//' /proc/$pid/cmdline | tr '\0' ' ' | xargs)
+  if [ -n "$fd" ]; then
+    if echo -n "$fd" | grep -E '[0-9]*'; then
+      lockfile=$(readlink /proc/$pid/fd/$fd)
+    else
+      lockfile="$fd"
+    fi
+    ppid=$(grep -i ^PPId /proc/$pid/status | cut -d: -f2 | xargs)
+    service=$(basename $(grep -oE '/etc/init.d/[^\0]*' /proc/$ppid/cmdline) 2>/dev/null)
+    if [ -n "$service" ]; then
+      if [ -e "$lockfile" ]; then
+        pids=$($LSOF $lockfile | grep $lockfile | grep -v "\b$pid\b\|\b$ppid\b" | tr -s ' ' | cut -d' ' -f2 | xargs echo $pid $ppid)
+      else
+        pids="$pid $ppid"
+      fi
+      echo -en "\033[2K\rINFO:     CLEARING file lock on $service service ${GREY}($lockfile)${NC}"
+      rm $lockfile 1>/dev/null 2>&1
+      for p in $pids; do
+        kill -9 $pids 1>/dev/null 2>&1
+      done
     fi
   fi
 done
-echo -en "\r$(date +%F@%X): STOPPED services"
-c=$(( $c + 31 - 26 ))
-while [ $c -gt 0 ]; do echo -n " "; c=$(( $c - 1 )); done
-echo
+echo -e "\033[2K\rINFO:     CLEARED service file locks${NC}"
 
-echo -e "$(date +%F@%X): ${ORANGE}REMOVING existing overlay...${NC}"
+for service in $(ls /etc/rc.d/K* | grep -v 'network\|umount'); do
+  exe=$(basename $(readlink $service) 2>/dev/null)
+  echo -en "\033[2K\rINFO:     STOPPING services: $(echo $sp | cut -c $i) ${GREY}$exe${NC}"
+  [ "$exe" = "cwmpd" ] && kill -9 $(pgrep cwmpd) 1>/dev/null 2>&1
+  $service stop 1>/dev/null 2>&1
+  [ $i -lt 4 ] && i=$(( $i + 1 )) || i=1
+done
+echo -e "\033[2K\rINFO:     STOPPED services"
+
+if [ -n "$(which lsof)" ]; then
+  lsof /overlay | awk '/ REG /{print $2}' | uniq | while read p; do
+    if [ -d "/proc/$p" ]; then
+      exe=$(readlink /proc/$p/exe)
+      echo -en "\033[2K\rINFO:     KILLING writing processes: $(echo $sp | cut -c $i) ${GREY}$exe ($p)${NC}"
+      kill -9 $p
+      [ $i -lt 4 ] && i=$(( $i + 1 )) || i=1
+    fi
+  done
+  echo -e "\033[2K\rINFO:     KILLED writing processes"
+fi
+
+echo -e "INFO:     ${ORANGE}REMOVING existing overlay...${NC}"
 cd /overlay
 rm -rf $RESTORE
 cd - >/dev/null
 
-echo -e "$(date +%F@%X): ${ORANGE}RESTORING...${NC}"
+echo -e "INFO:     ${ORANGE}RESTORING...${NC}"
 if tar -x${GZIP}${VERBOSE} -f $FILENAME -C /overlay $RESTORE; then
-  sync
-  echo -e "$(date +%F@%X): ${GREEN}COMPLETED${NC}"
-  echo -e "$(date +%F@%X): ${GREEN}CREATING post-boot configuration...${NC}"
+  echo -e "INFO:     ${GREEN}COMPLETED${NC}"
+  echo -e "INFO:     ${GREEN}CREATING post-boot configuration...${NC}"
   mkdir -p /overlay/$BOOTED/etc/uci-defaults
   mv $MAC_UCI /overlay/$BOOTED/etc/uci-defaults/zzz_9999-overlay-restore 
   if echo $RESTORE | grep -q $BOOTED; then
@@ -214,7 +231,7 @@ if tar -x${GZIP}${VERBOSE} -f $FILENAME -C /overlay $RESTORE; then
     sync
   fi
   if [ $REBOOT = Y ]; then
-    echo "$(date +%F@%X): REBOOTING..."
+    echo "INFO:     REBOOTING..."
     if [ -e /proc/sysrq-trigger ]; then
       sleep 1
       echo 1 > /proc/sys/kernel/sysrq
@@ -222,12 +239,13 @@ if tar -x${GZIP}${VERBOSE} -f $FILENAME -C /overlay $RESTORE; then
     else
       reboot
     fi
-    sleep 10
+    sleep 5
   else
-    echo -e "$(date +%F@%X): ${ORANGE}WARNING: Outstanding configuration changes not yet applied!${NC}"
-    echo "$(date +%F@%X): You should reboot as soon as possible."
+    echo -e "${ORANGE}WARNING:  Outstanding configuration changes not yet applied!${NC}"
+    echo -e "INFO:     ${ORANGE}You should reboot as soon as possible.${NC}"
   fi
+  echo -e "INFO:     ${GREEN}DONE!${NC}"
 else
-  echo -e "$(date +%F@%X): ${RED}RESTORE FAILED!${NC}"
+  echo -e echo -e "${RED}ERROR:    RESTORE FAILED!${NC}"
   exit 1
 fi
