Re-sequenced reset/flash to fix command I/O errors

diff --git a/utilities/reset-to-factory-defaults-with-root b/utilities/reset-to-factory-defaults-with-root
--- a/utilities/reset-to-factory-defaults-with-root
+++ b/utilities/reset-to-factory-defaults-with-root
@@ -473,30 +473,16 @@ if [ $SWITCH_BANK = "Y" ]; then
   TARGET_MTD=${NOT_BOOTED}
 fi
 
-if [ -n "$FIRMWARE" ]; then
-  if [ "$ROM_FS" = "ubifs" ]; then
-    TARGET_BANK=/overlay/${NOT_BOOTED}
-    echo -e "INFO:     Writing ${ORANGE}$FIRMWARE${NC} into ${ORANGE}${NOT_BOOTED}${NC}..."
-    echo -en "${GREY}"
-    sysupgrade -n -v --no-reboot "$FIRMWARE"
-    VERIFY_RESULT=$?
-    echo -en "${NC}"
-    if [ "$VERIFY_RESULT" -ne 0 ]; then
-      echo -e "${RED}ABORTING: sysupgrade FAILED!!${NC}"
-      exit 2
-    fi
-  else
-    echo -e "INFO:     Writing ${ORANGE}$FIRMWARE${NC} into ${ORANGE}${TARGET_MTD}${NC}..."
-    echo -en "${GREY}"
-    mtd -e ${TARGET_MTD} write "$FIRMWARE" ${TARGET_MTD}
-    echo -en "${NC}"
-    echo -e "INFO:     Verifying ${ORANGE}${TARGET_MTD}${NC} against ${ORANGE}$FIRMWARE${NC}..."
-    VERIFY_RESULT=$(mtd verify "$FIRMWARE" ${TARGET_MTD} 2>&1)
-    echo -e "${GREY}$VERIFY_RESULT${NC}"
-    if echo "$VERIFY_RESULT" | grep -q 'Failed'; then
-      echo -e "${RED}ABORTING: mtd verify FAILED!!${NC}"
-      exit 2
-    fi
+if [ -n "$FIRMWARE" -a "$ROM_FS" = "ubifs" ]; then
+  TARGET_BANK=/overlay/${NOT_BOOTED}
+  echo -e "INFO:     Writing ${ORANGE}$FIRMWARE${NC} into ${ORANGE}${NOT_BOOTED}${NC}..."
+  echo -en "${GREY}"
+  sysupgrade -n -v --no-reboot "$FIRMWARE"
+  VERIFY_RESULT=$?
+  echo -en "${NC}"
+  if [ "$VERIFY_RESULT" -ne 0 ]; then
+    echo -e "${RED}ABORTING: sysupgrade FAILED!!${NC}"
+    exit 2
   fi
 fi
 
@@ -542,6 +528,20 @@ if [ $__VERBOSE = Y ]; then
   echo -en "${NC}"
 fi
 echo -e "${GREEN}INFO:     Device has been reset to factory defaults and root access retained${NC}"
+
+if [ -n "$FIRMWARE" -a "$ROM_FS" = "squashfs" ]; then
+  echo -e "INFO:     Writing ${ORANGE}$FIRMWARE${NC} into ${ORANGE}${TARGET_MTD}${NC}..."
+  echo -en "${GREY}"
+  mtd -e ${TARGET_MTD} write "$FIRMWARE" ${TARGET_MTD}
+  echo -en "${NC}"
+  echo -e "INFO:     Verifying ${ORANGE}${TARGET_MTD}${NC} against ${ORANGE}$FIRMWARE${NC}..."
+  VERIFY_RESULT=$(mtd verify "$FIRMWARE" ${TARGET_MTD} 2>&1)
+  echo -e "${GREY}$VERIFY_RESULT${NC}"
+  if echo "$VERIFY_RESULT" | grep -q 'Failed'; then
+    echo -e "${RED}ABORTING: mtd verify FAILED!!${NC}"
+    exit 2
+  fi
+fi
 
 if [ $SWITCH_BANK = "Y" ]; then
   echo -e "INFO:     Switching active bank to ${GREEN}bank_$PASSIVE${NC}"
