Check for existence of overlay and config backup

diff --git a/utilities/reset-to-factory-defaults-with-root b/utilities/reset-to-factory-defaults-with-root
--- a/utilities/reset-to-factory-defaults-with-root
+++ b/utilities/reset-to-factory-defaults-with-root
@@ -151,12 +151,19 @@ if [ $RESTORE_CONFIG = y ]; then
         echo -e "${RED}ABORTING: Configuration restore requested, but no overlay backups for serial number $DEVICE_SERIAL found!${NC}"
         exit
       fi
-    elif ! echo "$1" | grep -q 'overlay-files-backup.tgz$'; then
-      echo -e "${RED}ABORTING: Configuration restore requested,  $1 is not an overlay files backup!${NC}"
-      exit
+    elif [ ! -e "$1" ]; then
+      echo -e "${RED}ABORTING: Configuration restore requested, but $1 does not exist!${NC}"
     else
       RESTORE_OPTIONS="$(cd $(dirname $1);pwd)/$(basename $1)"
     fi
+    if ! echo "$RESTORE_OPTIONS" | grep -q 'overlay-files-backup.tgz$'; then
+      echo -e "${RED}ABORTING: Configuration restore requested, but $1 is not an overlay files backup!${NC}"
+      exit
+    fi
+    if [ ! -e "${RESTORE_OPTIONS%-overlay-files-backup.tgz}-config.gz" ]; then
+      echo -e "${RED}ABORTING: $RESTORE_OPTIONS found, but ${RESTORE_OPTIONS%-overlay-files-backup.tgz}-config.gz does not exist!${NC}"
+    fi
+    OVERLAY_BACKUP=$(basename $RESTORE_OPTIONS | cut -d- -f1-3)
     if [ -n "$__IPADDR" ]; then
       RESTORE_OPTIONS="-i $__IPADDR $RESTORE_OPTIONS"
       __IPADDR=""
@@ -208,7 +215,7 @@ if [ -n "$FIRMWARE" ]; then
   fi
 fi
 
-echo -e "NOTE:    root access will be preserved. root password will be reset to '${GREEN}${__ROOTPWD}${NC}'"
+echo -e "NOTE:    Root access will be preserved. The root password will be reset to '${GREEN}${__ROOTPWD}${NC}'"
 LAN_CFG="echo 'Configuring root SSH access'"
 if [ -n "$__IPADDR" ]; then
   IPPREFIX="$(echo $__IPADDR | cut -d. -f1-3)"
@@ -227,17 +234,17 @@ if [ -n "$__CWMP" ]; then
   CWMP_CFG="echo 'Disabling CWMP';uci set cwmpd.cwmpd_config.state='0';uci commit cwmpd;/etc/init.d/cwmpd stop &"
 fi
 if [ -n "$__NOEXEC" ]; then
-  echo -e "NOTE:    Any 'noexec' flags will be ${GREEN}removed${NC} from USB filesystem mounts after reset"
+  echo -e "NOTE:    Any 'noexec' flags will be ${ORANGE}removed${NC} from USB filesystem mounts after reset"
   NOEXEC_CFG="echo 'Removing noexec mount flags';sed -e 's/noexec,//' -e 's/,noexec//' -i /etc/config/mountd"
 fi
 if [ -n "$__KEYS" ]; then
-  echo -e "NOTE:    SSH keys will be ${GREEN}restored${NC} after reset:"
-  KEYS_CFG="echo 'Restoring SSH keys';echo '$(tar -czvf - -C / etc/dropbear | base64 | tr -d "$IFS")' | base64 -d | tar -xzvf - -C /"
+  echo -e "NOTE:    SSH keys will be ${GREEN}restored${NC} after reset: ${GREEN}$(ls /etc/dropbear | xargs)${NC}"
+  KEYS_CFG="echo 'Restoring SSH keys';echo '$(tar -czf - -C / etc/dropbear | base64 | tr -d "$IFS")' | base64 -d | tar -xzvf - -C /"
 fi
 if [ $RESTORE_CONFIG = y ]; then
-  echo -e "${ORANGE}WARNING: Configuration backup will be restored to the device using options: ${RESTORE_OPTIONS}${NC}"
-  echo -e "${ORANGE}         The device MUST have internet access after factory reset or the configuration restore will FAIL!${NC}"
-
+  echo -e "NOTE:    Configuration backup ${GREEN}${OVERLAY_BACKUP}${NC} will be restored to the device!"
+  echo -e "${ORANGE}WARNING: The device MUST have internet access after factory reset or the configuration restore will ${RED}FAIL!${NC}"
+  echo "COMMAND: ${MOUNT_PATH}${USB}/backups/restore-config ${RESTORE_OPTIONS}"
   RESTORE_CFG="(while [ -e /etc/rc.local -a ! -e ${MOUNT_PATH}${USB}/backups/restore-config.sh ]; do sleep 2; done; sh ${MOUNT_PATH}${USB}/backups/restore-config.sh -vvy $RESTORE_OPTIONS 2>&1 | logger -t restore-config) &"
 else
   echo -e "${ORANGE}WARNING: You are resetting to factory defaults!${NC}"
@@ -245,7 +252,11 @@ else
   grep -q 'tch-gui-unhide' /www/docroot/gateway.lp && echo "NOTE:    You will also need to re-run tch-gui-unhide after rebooting!"
 fi
 if [ "$__REBOOT" = "Y" ]; then
-  echo -e "${ORANGE}WARNING: Device will attempt to reboot!${NC}"
+  if [ $RESTORE_CONFIG = y ]; then
+    echo -e "${ORANGE}WARNING: The device will reboot ${GREEN}TWICE${ORANGE} to apply the restored configuration!${NC}"
+  else
+    echo -e "${ORANGE}WARNING: The device will be rebooted using SysRQ trigger!${NC}"
+  fi
 fi
 echo
 echo -n -e "${GREEN}ACTION:  Enter y to continue, or anything else to exit now${NC} "
