Allow override of build version

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -1,5 +1,24 @@
 #!/bin/sh
 
+DATE_VERSION=$(date +%Y.%m.%d)
+FULL_VERSION=$(date +%Y.%m.%d@%H:%M:%S)
+
+while getopts v: option
+do
+  case $option in
+    v)  echo $OPTARG | grep -q -E '^[0-9][0-9][0-9][0-9]\.[0-1][0-9]\.[0-3][0-9]$'
+        if [ $? -eq 1 ]; then
+          echo "ERROR: -v option requires a parameter in the format YYYY.MM.DD"
+          exit
+        else
+          DATE_VERSION="$OPTARG"
+          FULL_VERSION="$DATE_VERSION@$(date +%H:%M:%S)"
+          echo "Overriding Release - using $FULL_VERSION"
+        fi;;
+  esac
+done
+shift $((OPTIND-1))
+
 DIR=$(pwd)
 
 echo Cleaning up..
@@ -30,7 +49,7 @@ do
 done
 echo "" >> $TARGET
 
-sed -e "s/current_version = \"\"/current_version = \"$(date +%Y.%m.%d@%H:%M:%S)\"/" -i $(find /tmp/additional -name gui.map)
+sed -e "s/current_version = \"\"/current_version = \"$FULL_VERSION\"/" -i $(find /tmp/additional -name gui.map)
 
 for d in $(ls /tmp/additional)
 do
@@ -65,7 +84,8 @@ do
 
   echo Writing $TARGET...
   echo "#!/bin/sh" > $TARGET
-  echo "echo 000@\$(date +%H:%M:%S): Built for version $MAJOR.$MINOR - Release $(date +%Y.%m.%d)" >> $TARGET
+  echo "echo 000@\$(date +%H:%M:%S): Built for firmware version $MAJOR.$MINOR - Release $DATE_VERSION" >> $TARGET
+  echo "RELEASE='$FULL_VERSION'" >> $TARGET
 
   for s in $(find . -mindepth 2 -type f -a ! -name .do-not-delete -exec sh -c 'echo $(basename {})$(dirname {} | cut -c2-)' \; | sort)
   do
@@ -91,7 +111,7 @@ do
           echo "  for l in \$(grep -l -r 'current_year); ngx.print(' /www 2>/dev/null)" >> $TARGET
           echo "  do" >> $TARGET
           echo "    echo $SEQUENCE@\$(date +%H:%M:%S): Adding tch-gui-unhide version to copyright in \$l" >> $TARGET
-          echo "    sed -e \"s/\(current_year); ngx.print('\)/\\\1 \[tch-gui-unhide $(date +%Y.%m.%d) for FW Version $MAJOR.$MINOR\]/\" -i \$l" >> $TARGET
+          echo "    sed -e \"s/\(current_year); ngx.print('\)/\\\1 \[tch-gui-unhide $DATE_VERSION for FW Version $MAJOR.$MINOR\]/\" -i \$l" >> $TARGET
           echo "  done" >> $TARGET
           echo "fi" >> $TARGET
           echo >> $TARGET
@@ -104,4 +124,4 @@ done
 
 echo Cleaning up..
 rm -rf /tmp/additional ../additional/*.b64
-echo Build Complete @ $(date +%H:%M:%S) for version $(date +%Y.%m.%d)
+echo Build Complete @ $(date +%H:%M:%S) for version $FULL_VERSION
